import { MejoresAtaquesModel } from "./zzzmejoresAataques.model";



export class MejoresAtaquesIniciales {

 misMejoresAtaquesIniciales: MejoresAtaquesModel[] = [
        new MejoresAtaquesModel("Abomasnow", "Hoja afilada"),
new MejoresAtaquesModel("Abomasnow", "Meteorobola Hielo"),
new MejoresAtaquesModel("Abomasnow", "Ventisca"),
new MejoresAtaquesModel("Absol", "Alarido"),
new MejoresAtaquesModel("Absol", "Vendetta"),
new MejoresAtaquesModel("Accelgor", "Ácido"),
new MejoresAtaquesModel("Accelgor", "Onda Certera"),
new MejoresAtaquesModel("Aerodactyl", "Avalancha"),
new MejoresAtaquesModel("Aerodactyl", "Hiperrayo"),
new MejoresAtaquesModel("Aerodactyl", "Lanzarrocas"),
new MejoresAtaquesModel("Aggron", "Antiaéreo"),
new MejoresAtaquesModel("Aggron", "Cola Férrea"),
new MejoresAtaquesModel("Aggron", "Roca Afilada"),
new MejoresAtaquesModel("Alakazam", "Confusión"),
new MejoresAtaquesModel("Alakazam", "Premonición"),
new MejoresAtaquesModel("Ambipom", "Arañazo"),
new MejoresAtaquesModel("Ambipom", "Hiperrayo"),
new MejoresAtaquesModel("Amoonguss", "Bomba Lodo"),
new MejoresAtaquesModel("Amoonguss", "Finta"),
new MejoresAtaquesModel("Amoonguss", "Hierba Lazo"),
new MejoresAtaquesModel("Ampharos", "Electrocañón"),
new MejoresAtaquesModel("Ampharos", "Pulso Dragón"),
new MejoresAtaquesModel("Ampharos", "Trueno"),
new MejoresAtaquesModel("Ampharos", "Voltiocambio"),
new MejoresAtaquesModel("Annihilape", "A Bocajarro"),
new MejoresAtaquesModel("Annihilape", "Contraataque"),
new MejoresAtaquesModel("Arboliva", "Bomba Germen"),
new MejoresAtaquesModel("Arboliva", "Energibola"),
new MejoresAtaquesModel("Arboliva", "Hoja Afilada"),
new MejoresAtaquesModel("Arboliva", "Tierra Viva"),
new MejoresAtaquesModel("Arcanine", "Colmillo Ígneo"),
new MejoresAtaquesModel("Arcanine", "Lanzallamas"),
new MejoresAtaquesModel("Arcanine", "Llamarada"),
new MejoresAtaquesModel("Armaldo", "Estoicismo"),
new MejoresAtaquesModel("Armaldo", "Pedrada"),
new MejoresAtaquesModel("Armaldo", "Veneno X"),
new MejoresAtaquesModel("Aromatisse", "Encanto"),
new MejoresAtaquesModel("Aromatisse", "Fuerza Lunar"),
new MejoresAtaquesModel("Articuno", "Canto Helado"),
new MejoresAtaquesModel("Articuno", "Vaho Gélido"),
new MejoresAtaquesModel("Articuno", "Vendaval"),
new MejoresAtaquesModel("Articuno", "Ventisca"),
new MejoresAtaquesModel("Avalugg", "Alud"),
new MejoresAtaquesModel("Avalugg", "Mordisco"),
new MejoresAtaquesModel("Avalugg", "Terremoto"),
new MejoresAtaquesModel("Banette", "Bola Sombra"),
new MejoresAtaquesModel("Banette", "Garra Umbría"),
new MejoresAtaquesModel("Banette", "Trueno"),
new MejoresAtaquesModel("Barbaracle", "Bofetón Lodo"),
new MejoresAtaquesModel("Barbaracle", "Pistola Agua"),
new MejoresAtaquesModel("Barbaracle", "Roca Afilada"),
new MejoresAtaquesModel("Baxcalibur", "Alud"),
new MejoresAtaquesModel("Baxcalibur", "Dragoaliento"),
new MejoresAtaquesModel("Baxcalibur", "Ventisca"),
new MejoresAtaquesModel("Beartic", "Encanto"),
new MejoresAtaquesModel("Beartic", "Surf"),
new MejoresAtaquesModel("Beheeyem", "Confusión"),
new MejoresAtaquesModel("Beheeyem", "Psíquico"),
new MejoresAtaquesModel("Bellibol", "Chispazo"),
new MejoresAtaquesModel("Bellibol", "Impactrueno"),
new MejoresAtaquesModel("Blastoise", "Cabezazo"),
new MejoresAtaquesModel("Blastoise", "Hidrobomba"),
new MejoresAtaquesModel("Blastoise", "Hidrocañón"),
new MejoresAtaquesModel("Blastoise", "Mordisco"),
new MejoresAtaquesModel("Blastoise", "Pistola Agua"),
new MejoresAtaquesModel("Blaziken", "Contraataque"),
new MejoresAtaquesModel("Blaziken", "Giro fuego"),
new MejoresAtaquesModel("Blaziken", "Pájaro osado"),
new MejoresAtaquesModel("Blissey", "Destructor"),
new MejoresAtaquesModel("Blissey", "Hiperrayo"),
new MejoresAtaquesModel("Braviary", "Ala de Acero"),
new MejoresAtaquesModel("Braviary", "Pájaro Osado"),
new MejoresAtaquesModel("Braviary", "Tajo Aéreo"),
new MejoresAtaquesModel("Breloom", "Contraataque"),
new MejoresAtaquesModel("Breloom", "Hierba Lazo"),
new MejoresAtaquesModel("Breloom", "Puño dinámico"),
new MejoresAtaquesModel("Buzzwole", "Contraataque"),
new MejoresAtaquesModel("Buzzwole", "Fuerza Bruta"),
new MejoresAtaquesModel("Buzzwole", "Puño Incremento"),
new MejoresAtaquesModel("Cacturne", "Golpe bajo"),
new MejoresAtaquesModel("Cacturne", "Hierba lazo"),
new MejoresAtaquesModel("Cacturne", "Puya nociva"),
new MejoresAtaquesModel("Chandelure", "Calcinación"),
new MejoresAtaquesModel("Chandelure", "Giro fuego"),
new MejoresAtaquesModel("Chandelure", "Sofoco"),
new MejoresAtaquesModel("Charizard", "Giro fuego"),
new MejoresAtaquesModel("Charizard", "Sofoco"),
new MejoresAtaquesModel("Charizard", "Tajo Aéreo"),
new MejoresAtaquesModel("Chesnaught", "Hoja afilada"),
new MejoresAtaquesModel("Chesnaught", "Látigo Cepa"),
new MejoresAtaquesModel("Chesnaught", "Rayo solar"),
new MejoresAtaquesModel("Cinccino", "Destructor"),
new MejoresAtaquesModel("Cinccino", "Encanto"),
new MejoresAtaquesModel("Cinccino", "Hiperrayo"),
new MejoresAtaquesModel("Clawitzer", "Antiaéreo"),
new MejoresAtaquesModel("Clawitzer", "Martillazo"),
new MejoresAtaquesModel("Clawitzer", "Pistola Agua"),
new MejoresAtaquesModel("Clefable", "Brillo mágico"),
new MejoresAtaquesModel("Clefable", "Encanto"),
new MejoresAtaquesModel("Clefable", "Fuerza lunar"),
new MejoresAtaquesModel("Clefable", "Puño meteoro"),
new MejoresAtaquesModel("Cloyster", "Canto helado"),
new MejoresAtaquesModel("Cloyster", "Hidrobomba"),
new MejoresAtaquesModel("Cloyster", "Vaho Gélido"),
new MejoresAtaquesModel("Cloyster", "Ventisca"),
new MejoresAtaquesModel("Conkeldurr", "Contraataque"),
new MejoresAtaquesModel("Conkeldurr", "Onda Certera"),
new MejoresAtaquesModel("Crabominable", "Golpe Roca"),
new MejoresAtaquesModel("Crabominable", "Martillazo"),
new MejoresAtaquesModel("Crabominable", "Vendetta"),
new MejoresAtaquesModel("Cradily", "Ácido"),
new MejoresAtaquesModel("Cradily", "Acoso"),
new MejoresAtaquesModel("Cradily", "Roca Afilada"),
new MejoresAtaquesModel("Crawdaunt", "Cascada"),
new MejoresAtaquesModel("Crawdaunt", "Martillazo"),
new MejoresAtaquesModel("Cresselia", "Confusión"),
new MejoresAtaquesModel("Cresselia", "Premonición"),
new MejoresAtaquesModel("Crobat", "Bomba lodo"),
new MejoresAtaquesModel("Crobat", "Mordisco"),
new MejoresAtaquesModel("Crobat", "Tajo Aéreo"),
new MejoresAtaquesModel("Crustle", "Antiaéreo"),
new MejoresAtaquesModel("Crustle", "Avalancha"),
new MejoresAtaquesModel("Crustle", "Tijera X"),
new MejoresAtaquesModel("Cryogonal", "Canto Helado"),
new MejoresAtaquesModel("Cryogonal", "Rayo Aurora"),
new MejoresAtaquesModel("Cryogonal", "Rayo Solar"),
new MejoresAtaquesModel("Cryogonal", "Triple Axel"),
new MejoresAtaquesModel("Cryogonal", "Vaho Gélido"),
new MejoresAtaquesModel("Darkrai", "Alarido"),
new MejoresAtaquesModel("Darkrai", "Finta"),
new MejoresAtaquesModel("Darkrai", "Onda certera"),
new MejoresAtaquesModel("Darmanitan - Standard", "Calcinación"),
new MejoresAtaquesModel("Darmanitan - Standard", "Colmillo Ígneo"),
new MejoresAtaquesModel("Darmanitan - Standard", "Sofoco"),
new MejoresAtaquesModel("Decidueye", "Hoja Afilada"),
new MejoresAtaquesModel("Decidueye", "Pájaro Osado"),
new MejoresAtaquesModel("Decidueye - Hisui", "Esfera Aural"),
new MejoresAtaquesModel("Decidueye - Hisui", "Hoja mágica"),
new MejoresAtaquesModel("Delphox", "Cabezazo Zen"),
new MejoresAtaquesModel("Delphox", "Giro fuego"),
new MejoresAtaquesModel("Delphox", "Lanzallamas"),
new MejoresAtaquesModel("Delphox", "Llamarada"),
new MejoresAtaquesModel("Delphox", "Nitrocarga"),
new MejoresAtaquesModel("Delphox", "Psíquico"),
new MejoresAtaquesModel("Dialga", "Cometa Draco"),
new MejoresAtaquesModel("Dialga", "Dragoaliento"),
new MejoresAtaquesModel("Dialga", "Garra Metal"),
new MejoresAtaquesModel("Dodrio", "Ala de acero"),
new MejoresAtaquesModel("Dodrio", "Pájaro osado"),
new MejoresAtaquesModel("Donphan", "Bofetón Lodo"),
new MejoresAtaquesModel("Donphan", "Terremoto"),
new MejoresAtaquesModel("Dragalge", "Cola Dragón"),
new MejoresAtaquesModel("Dragalge", "Lanzamugre"),
new MejoresAtaquesModel("Dragonite", "Cola Dragón"),
new MejoresAtaquesModel("Dragonite", "Cometa draco"),
new MejoresAtaquesModel("Dragonite", "Dragoaliento"),
new MejoresAtaquesModel("Dragonite", "Vendaval"),
new MejoresAtaquesModel("Drapion", "Bomba lodo"),
new MejoresAtaquesModel("Drapion", "Mordisco"),
new MejoresAtaquesModel("Drifblim", "Bola sombra"),
new MejoresAtaquesModel("Drifblim", "Infortunio"),
new MejoresAtaquesModel("Dusknoir", "Infortunio"),
new MejoresAtaquesModel("Dusknoir", "Psíquico"),
new MejoresAtaquesModel("Eelektross", "Ácido"),
new MejoresAtaquesModel("Eelektross", "Chispa"),
new MejoresAtaquesModel("Eelektross", "Rayo"),
new MejoresAtaquesModel("Electivire", "Impactrueno"),
new MejoresAtaquesModel("Electivire", "Patada baja"),
new MejoresAtaquesModel("Electivire", "Trueno"),
new MejoresAtaquesModel("Electrode Hisuain", "Impactrueno"),
new MejoresAtaquesModel("Electrode Hisuain", "Placaje"),
new MejoresAtaquesModel("Electrode Hisuain", "Voltio Cruel"),
new MejoresAtaquesModel("Emboar", "Impactrueno"),
new MejoresAtaquesModel("Emboar", "Patada baja"),
new MejoresAtaquesModel("Emboar", "Trueno"),
new MejoresAtaquesModel("Empoleon", "Cascada"),
new MejoresAtaquesModel("Empoleon", "Hidrobomba"),
new MejoresAtaquesModel("Empoleon", "Hidrocañón"),
new MejoresAtaquesModel("Entei", "Colmillo Ígneo"),
new MejoresAtaquesModel("Entei", "Giro Fuego"),
new MejoresAtaquesModel("Entei", "Llamarada"),
new MejoresAtaquesModel("Entei", "Sofoco"),
new MejoresAtaquesModel("Escavalier", "Contraataque"),
new MejoresAtaquesModel("Escavalier", "Picadura"),
new MejoresAtaquesModel("Espeon", "Confusión"),
new MejoresAtaquesModel("Espeon", "Premonición"),
new MejoresAtaquesModel("Excadrill", "Bofetón Lodo"),
new MejoresAtaquesModel("Excadrill", "Garra Metal"),
new MejoresAtaquesModel("Excadrill", "Terremoto"),
new MejoresAtaquesModel("Exeggutor Alola", "Cola Dragón"),
new MejoresAtaquesModel("Exeggutor Alola", "Rayo Solar"),
new MejoresAtaquesModel("Exeggutor normal", "Cabezazo Zen"),
new MejoresAtaquesModel("Exeggutor normal", "Confusión"),
new MejoresAtaquesModel("Exeggutor normal", "Paranormal"),
new MejoresAtaquesModel("Exeggutor normal", "Rayo Solar"),
new MejoresAtaquesModel("Exploud", "Llamarada"),
new MejoresAtaquesModel("Exploud", "Mordisco"),
new MejoresAtaquesModel("Feraligatr", "Cascada"),
new MejoresAtaquesModel("Feraligatr", "Hidrobomba"),
new MejoresAtaquesModel("Feraligatr", "Hidrocañón"),
new MejoresAtaquesModel("Flareon", "Giro Fuego"),
new MejoresAtaquesModel("Flareon", "Sofoco"),
new MejoresAtaquesModel("Floatzel", "Cascada"),
new MejoresAtaquesModel("Floatzel", "Hidrobomba"),
new MejoresAtaquesModel("Florges - Blue", "Fuerza Lunar"),
new MejoresAtaquesModel("Florges - Blue", "Látigo Cepa"),
new MejoresAtaquesModel("Florges - Blue", "Tormenta Floral"),
new MejoresAtaquesModel("Florges - Orange", "Fuerza Lunar"),
new MejoresAtaquesModel("Florges - Orange", "Hoja Afilada"),
new MejoresAtaquesModel("Florges - Orange", "Látigo Cepa"),
new MejoresAtaquesModel("Florges - Orange", "Tormenta Floral"),
new MejoresAtaquesModel("Florges - Red", "Fuerza Lunar"),
new MejoresAtaquesModel("Florges - Red", "Hoja Afilada"),
new MejoresAtaquesModel("Florges - Red", "Látigo Cepa"),
new MejoresAtaquesModel("Florges - Red", "Tormenta Floral"),
new MejoresAtaquesModel("Florges . Yellow", "Fuerza Lunar"),
new MejoresAtaquesModel("Florges . Yellow", "Hoja Afilada"),
new MejoresAtaquesModel("Florges . Yellow", "Látigo Cepa"),
new MejoresAtaquesModel("Florges . Yellow", "Tormenta Floral"),
new MejoresAtaquesModel("Florges . Yellow", "Viento Feérico"),
new MejoresAtaquesModel("Flygon", "Cola Dragón"),
new MejoresAtaquesModel("Flygon", "Roca Afilada"),
new MejoresAtaquesModel("Flygon", "Terremoto"),
new MejoresAtaquesModel("Forretress", "Cuerpo Pesado"),
new MejoresAtaquesModel("Forretress", "Estoicismo"),
new MejoresAtaquesModel("Forretress", "Picadura"),
new MejoresAtaquesModel("Forretress", "Terremoto"),
new MejoresAtaquesModel("Gallade", "A Bocajarro"),
new MejoresAtaquesModel("Gallade", "Confusión"),
new MejoresAtaquesModel("Garbodor", "Acoso"),
new MejoresAtaquesModel("Garbodor", "Lanzamugre"),
new MejoresAtaquesModel("Garchomp", "Cola Dragón"),
new MejoresAtaquesModel("Garchomp", "Terremoto"),
new MejoresAtaquesModel("Gardevoir", "Brillo Mágico"),
new MejoresAtaquesModel("Gardevoir", "Confusión"),
new MejoresAtaquesModel("Gardevoir", "Encanto"),
new MejoresAtaquesModel("Gardevoir", "Psíquico"),
new MejoresAtaquesModel("Gardevoir", "Sincrorruido"),
new MejoresAtaquesModel("Gastrodom", "Bofetón Lodo"),
new MejoresAtaquesModel("Gastrodom", "Tierra Viva"),
new MejoresAtaquesModel("Genesect", "Garra Metal"),
new MejoresAtaquesModel("Genesect", "Hiperrayo"),
new MejoresAtaquesModel("Gengar", "Bola Sombra"),
new MejoresAtaquesModel("Gengar", "Bomba Lodo"),
new MejoresAtaquesModel("Gengar", "Garra Umbría"),
new MejoresAtaquesModel("Gengar", "Onda Certera"),
new MejoresAtaquesModel("Gengar", "Onda Tóxica"),
new MejoresAtaquesModel("Gigalith", "Antiaéreo"),
new MejoresAtaquesModel("Gigalith", "Avalancha"),
new MejoresAtaquesModel("Gigalith", "Cuerpo Pesado"),
new MejoresAtaquesModel("Gigalith", "Rayo Solar"),
new MejoresAtaquesModel("Giratina", "Dragoaliento"),
new MejoresAtaquesModel("Giratina", "Garra Dragón"),
new MejoresAtaquesModel("Giratina", "Garra Umbría"),
new MejoresAtaquesModel("Giratina Altered", "Dragoaliento"),
new MejoresAtaquesModel("Giratina Altered", "Garra Dragón"),
new MejoresAtaquesModel("Giratina Altered", "Garra Umbría"),
new MejoresAtaquesModel("Giratina Origen", "Bola Sombra"),
new MejoresAtaquesModel("Giratina Origen", "Cola Dragón"),
new MejoresAtaquesModel("Giratina Origen", "Garra Umbría"),
new MejoresAtaquesModel("Glaceon", "Alud"),
new MejoresAtaquesModel("Glaceon", "Canto Helado"),
new MejoresAtaquesModel("Glaceon", "Vaho Gélido"),
new MejoresAtaquesModel("Gliscor", "Ataque Ala"),
new MejoresAtaquesModel("Gliscor", "Terremoto"),
new MejoresAtaquesModel("Golduck", "Confusión"),
new MejoresAtaquesModel("Golduck", "Hidrobomba"),
new MejoresAtaquesModel("Golduck", "Pistola Agua"),
new MejoresAtaquesModel("Golem Alola", "Desenrrollar"),
new MejoresAtaquesModel("Golem Alola", "Lanzarrocas"),
new MejoresAtaquesModel("Golem Alola", "Roca Afilada"),
new MejoresAtaquesModel("Golem Normal", "Bofetón Lodo"),
new MejoresAtaquesModel("Golem Normal", "Lanzarrocas"),
new MejoresAtaquesModel("Golem Normal", "Roca Afilada"),
new MejoresAtaquesModel("Golem Normal", "Terremoto"),
new MejoresAtaquesModel("Golisopod", "Cascada"),
new MejoresAtaquesModel("Golisopod", "Tijera X"),
new MejoresAtaquesModel("Golurk", "Bofetón Lodo"),
new MejoresAtaquesModel("Golurk", "Puño Dinámico"),
new MejoresAtaquesModel("Golurk", "Tierra viva"),
new MejoresAtaquesModel("Gothielle", "Confusión"),
new MejoresAtaquesModel("Gothielle", "Encanto"),
new MejoresAtaquesModel("Gothielle", "Premonición"),
new MejoresAtaquesModel("Gourgeist", "Bola Sombra"),
new MejoresAtaquesModel("Gourgeist", "Hoja Afilada"),
new MejoresAtaquesModel("Granbull", "A Bocajarro"),
new MejoresAtaquesModel("Granbull", "Encanto"),
new MejoresAtaquesModel("Greninja", "Burbuja"),
new MejoresAtaquesModel("Greninja", "Finta"),
new MejoresAtaquesModel("Greninja", "Hidrobomba"),
new MejoresAtaquesModel("Greninja", "Surf"),
new MejoresAtaquesModel("Groudon", "Cola Dragón"),
new MejoresAtaquesModel("Groudon", "Terremoto"),
new MejoresAtaquesModel("Grumpig", "Bola Sombra"),
new MejoresAtaquesModel("Grumpig", "Paranormal"),
new MejoresAtaquesModel("Grumpig", "Psíquico"),
new MejoresAtaquesModel("Gumshoos", "Hipercolmillo"),
new MejoresAtaquesModel("Gumshoos", "Mordisco"),
new MejoresAtaquesModel("Gyarados", "Cascada"),
new MejoresAtaquesModel("Gyarados", "Hidrobomba"),
new MejoresAtaquesModel("Hariyama", "A Bocajarro"),
new MejoresAtaquesModel("Hariyama", "Contraataque"),
new MejoresAtaquesModel("Haxorus", "Cola Dragón"),
new MejoresAtaquesModel("Haxorus", "Garra Dragón"),
new MejoresAtaquesModel("Haxorus", "Surf"),
new MejoresAtaquesModel("Haxorus", "Terremoto"),
new MejoresAtaquesModel("Haxorus", "Vasto Impacto"),
new MejoresAtaquesModel("Heatmor", "Giro Fuego"),
new MejoresAtaquesModel("Heatmor", "Lanzallamas"),
new MejoresAtaquesModel("Heatran", "Giro Fuego"),
new MejoresAtaquesModel("Heatran", "Llamarada"),
new MejoresAtaquesModel("Heatran", "Roca Afilada"),
new MejoresAtaquesModel("Heliolisk", "Ataque Rápido"),
new MejoresAtaquesModel("Heliolisk", "Bofetón Lodo"),
new MejoresAtaquesModel("Heliolisk", "Hierba Lazo"),
new MejoresAtaquesModel("Heliolisk", "Rayo"),
new MejoresAtaquesModel("Heracross", "A Bocajarro"),
new MejoresAtaquesModel("Heracross", "Contraataque"),
new MejoresAtaquesModel("Heracross", "Megacuerno"),
new MejoresAtaquesModel("Hippodown", "Colmillo Ígneo"),
new MejoresAtaquesModel("Hippodown", "Mordisco"),
new MejoresAtaquesModel("Hippodown", "Roca Afilada"),
new MejoresAtaquesModel("Hippodown", "Terremoto"),
new MejoresAtaquesModel("Hitmonchan", "A Bocajarro"),
new MejoresAtaquesModel("Hitmonchan", "Contraataque"),
new MejoresAtaquesModel("Hitmonlee", "A Bocajarro"),
new MejoresAtaquesModel("Hitmonlee", "Golpe Roca"),
new MejoresAtaquesModel("Hitmonlee", "Patada Baja"),
new MejoresAtaquesModel("Honchkrow", "Alarido"),
new MejoresAtaquesModel("Honchkrow", "Pájaro Osado"),
new MejoresAtaquesModel("Honchkrow", "Picotazo"),
new MejoresAtaquesModel("Houndoom", "Colmillo Ígneo"),
new MejoresAtaquesModel("Houndoom", "Juego Sucio"),
new MejoresAtaquesModel("Houndoom", "Llamarada"),
new MejoresAtaquesModel("Hydreigon", "Dragoaliento"),
new MejoresAtaquesModel("Hydreigon", "Foco Resplandor"),
new MejoresAtaquesModel("Hydreigon", "Giro vil"),
new MejoresAtaquesModel("Hydreigon", "Mordisco"),
new MejoresAtaquesModel("Incineroar", "Alarido"),
new MejoresAtaquesModel("Incineroar", "Colmillo Ígneo"),
new MejoresAtaquesModel("Incineroar", "Llamarada"),
new MejoresAtaquesModel("Infernape", "A Bocajarro"),
new MejoresAtaquesModel("Infernape", "Anillo Ígneo"),
new MejoresAtaquesModel("Infernape", "Giro Fuego"),
new MejoresAtaquesModel("Infernape", "Golpe Roca"),
new MejoresAtaquesModel("Jolteon", "Impactrueno"),
new MejoresAtaquesModel("Jolteon", "Trueno"),
new MejoresAtaquesModel("Jolteon", "Voltiocambio"),
new MejoresAtaquesModel("Jynx", "Alud"),
new MejoresAtaquesModel("Jynx", "Confusión"),
new MejoresAtaquesModel("Jynx", "Onda Certera"),
new MejoresAtaquesModel("Jynx", "Vaho Gélido"),
new MejoresAtaquesModel("Kabutops", "Cascada"),
new MejoresAtaquesModel("Kabutops", "Roca Afilada"),
new MejoresAtaquesModel("Kangaskhan", "Bofetón Lodo"),
new MejoresAtaquesModel("Kangaskhan", "Pisotón"),
new MejoresAtaquesModel("Kangaskhan", "Terremoto"),
new MejoresAtaquesModel("Kingdra", "Cascada"),
new MejoresAtaquesModel("Kingdra", "Dragoaliento"),
new MejoresAtaquesModel("Kingdra", "Hidrobomba"),
new MejoresAtaquesModel("Kingdra", "Ventisca"),
new MejoresAtaquesModel("Kingler", "Burbuja"),
new MejoresAtaquesModel("Kingler", "Garra Metal"),
new MejoresAtaquesModel("Kingler", "Martillazo"),
new MejoresAtaquesModel("Kyogre", "Cascada"),
new MejoresAtaquesModel("Kyogre", "Hidrobomba"),
new MejoresAtaquesModel("Kyogre", "Surf"),
new MejoresAtaquesModel("Kyogre", "Trueno"),
new MejoresAtaquesModel("Kyogre", "Ventisca"),
new MejoresAtaquesModel("Kyurem", "Ala de Acero"),
new MejoresAtaquesModel("Kyurem", "Cometa Draco"),
new MejoresAtaquesModel("Kyurem", "Dragoaliento"),
new MejoresAtaquesModel("Kyurem", "Ventisca"),
new MejoresAtaquesModel("Landorus", "Lanzarrocas"),
new MejoresAtaquesModel("Landorus", "Onda Certera"),
new MejoresAtaquesModel("Landorus Therian", "Lanzarrocas"),
new MejoresAtaquesModel("Landorus Therian", "Onda Certera"),
new MejoresAtaquesModel("Landorus Therian", "Roca Afilada"),
new MejoresAtaquesModel("Landorus Therian", "Terremoto"),
new MejoresAtaquesModel("Lapras", "Canto Helado"),
new MejoresAtaquesModel("Lapras", "Hidrobomba"),
new MejoresAtaquesModel("Lapras", "Pistola Agua"),
new MejoresAtaquesModel("Lapras", "Surf"),
new MejoresAtaquesModel("Lapras", "Vaho Gélido"),
new MejoresAtaquesModel("Lapras", "Ventisca"),
new MejoresAtaquesModel("Latias", "Cabezazo Zen"),
new MejoresAtaquesModel("Latias", "Dragoaliento"),
new MejoresAtaquesModel("Latias", "Encanto"),
new MejoresAtaquesModel("Latias", "Psíquico"),
new MejoresAtaquesModel("Latias", "Trueno"),
new MejoresAtaquesModel("Latios", "Cabezazo Zen"),
new MejoresAtaquesModel("Latios", "Dragoaliento"),
new MejoresAtaquesModel("Latios", "Garra Dragón"),
new MejoresAtaquesModel("Latios", "Psíquico"),
new MejoresAtaquesModel("Latios", "Rayo Solar"),
new MejoresAtaquesModel("Leafeon", "Hoja Afilada"),
new MejoresAtaquesModel("Leafeon", "Rayo Solar"),
new MejoresAtaquesModel("Lickilicky", "Cabezazo Zen"),
new MejoresAtaquesModel("Lickilicky", "Hiperrayo"),
new MejoresAtaquesModel("Lickilicky", "Lengüetazo"),
new MejoresAtaquesModel("Lilligant", "Encanto"),
new MejoresAtaquesModel("Lilligant", "Tormenta Floral"),
new MejoresAtaquesModel("Ludicolo", "Hidrobomba"),
new MejoresAtaquesModel("Ludicolo", "Hoja Afilada"),
new MejoresAtaquesModel("Ludicolo", "Rayo Solar"),
new MejoresAtaquesModel("Ludicolo", "Ventisca"),
new MejoresAtaquesModel("Lugia", "Aerochorro"),
new MejoresAtaquesModel("Lugia", "Ataque Aéreo"),
new MejoresAtaquesModel("Lugia", "Cola Dragón"),
new MejoresAtaquesModel("Lugia", "Paranormal"),
new MejoresAtaquesModel("Lugia", "Premonición"),
new MejoresAtaquesModel("Lycanroc Midday", "Lanzarrocas"),
new MejoresAtaquesModel("Lycanroc Midday", "Roca Afilada"),
new MejoresAtaquesModel("Machamp", "A Bocajarro"),
new MejoresAtaquesModel("Machamp", "Contraataque"),
new MejoresAtaquesModel("Machamp", "Vendetta"),
new MejoresAtaquesModel("Magmortar", "Giro Fuego"),
new MejoresAtaquesModel("Magmortar", "Llamarada"),
new MejoresAtaquesModel("Magnezone", "Chispa"),
new MejoresAtaquesModel("Magnezone", "Electrocañón"),
new MejoresAtaquesModel("Magnezone", "Foco Resplandor"),
new MejoresAtaquesModel("Magnezone", "Voltio Cruel"),
new MejoresAtaquesModel("Mamoswine", "Alud"),
new MejoresAtaquesModel("Mamoswine", "Bofetón Lodo"),
new MejoresAtaquesModel("Mamoswine", "Roca Afilada"),
new MejoresAtaquesModel("Manectric", "Alarido"),
new MejoresAtaquesModel("Manectric", "Trueno"),
new MejoresAtaquesModel("Masquerain", "Aire Afilado"),
new MejoresAtaquesModel("Masquerain", "Tajo Aéreo"),
new MejoresAtaquesModel("Meganium", "Hoja Afilada"),
new MejoresAtaquesModel("Meganium", "Látigo Cepa"),
new MejoresAtaquesModel("Meganium", "Planta Feroz"),
new MejoresAtaquesModel("Meganium", "Tormenta Floral"),
new MejoresAtaquesModel("Melmeltan", "Foco Resplandor"),
new MejoresAtaquesModel("Melmeltan", "Hiperrayo"),
new MejoresAtaquesModel("Melmeltan", "Impactrueno"),
new MejoresAtaquesModel("Meowscarada", "Encanto"),
new MejoresAtaquesModel("Meowscarada", "Follaje"),
new MejoresAtaquesModel("Meowscarada", "Hierba Lazo"),
new MejoresAtaquesModel("Metagross", "Cabezazo Zen"),
new MejoresAtaquesModel("Metagross", "Foco Resplandor"),
new MejoresAtaquesModel("Metagross", "Puño Bala"),
new MejoresAtaquesModel("Metagross", "Puño Meteoro"),
new MejoresAtaquesModel("Mewtwo", "Confusión"),
new MejoresAtaquesModel("Mewtwo", "Hiperrayo"),
new MejoresAtaquesModel("Mewtwo", "Onda Certera"),
new MejoresAtaquesModel("Mewtwo", "Onda mental"),
new MejoresAtaquesModel("Mewtwo", "Psíquico"),
new MejoresAtaquesModel("Miltank", "Cabezazo Zen"),
new MejoresAtaquesModel("Miltank", "Pisotón"),
new MejoresAtaquesModel("Miltank", "Placaje"),
new MejoresAtaquesModel("Mismagius", "Bola Sombra"),
new MejoresAtaquesModel("Mismagius", "Golpe Bajo"),
new MejoresAtaquesModel("Mismagius", "Infortunio"),
new MejoresAtaquesModel("Moltres", "Ataque Aéreo"),
new MejoresAtaquesModel("Moltres", "Giro Fuego"),
new MejoresAtaquesModel("Moltres", "Sofoco"),
new MejoresAtaquesModel("Mr.Mime", "Bola Sombra"),
new MejoresAtaquesModel("Mr.Mime", "Cabezazo Zen"),
new MejoresAtaquesModel("Mr.Mime", "Confusión"),
new MejoresAtaquesModel("Mr.Mime", "Psíquico"),
new MejoresAtaquesModel("Muk Alola", "Alarido"),
new MejoresAtaquesModel("Muk Alola", "Lanzamugre"),
new MejoresAtaquesModel("Muk Alola", "Mordisco"),
new MejoresAtaquesModel("Muk Alola", "Puya Nociva"),
new MejoresAtaquesModel("Muk Normal", "Ácido"),
new MejoresAtaquesModel("Muk Normal", "Lanzamugre"),
new MejoresAtaquesModel("Muk Normal", "Puya Nociva"),
new MejoresAtaquesModel("Musharna", "Cabezazo Zen"),
new MejoresAtaquesModel("Musharna", "Premonición"),
new MejoresAtaquesModel("Nidoking", "Cola Férrea"),
new MejoresAtaquesModel("Nidoking", "Megacuerno"),
new MejoresAtaquesModel("Nidoking", "Puya Nociva"),
new MejoresAtaquesModel("Nidoking", "Terremoto"),
new MejoresAtaquesModel("Nidoqueen", "Onda Tóxica"),
new MejoresAtaquesModel("Nidoqueen", "Puya Nociva"),
new MejoresAtaquesModel("Nidoqueen", "Roca Afilada"),
new MejoresAtaquesModel("Nidoqueen", "Terremoto"),
new MejoresAtaquesModel("Nihilego", "Ácido"),
new MejoresAtaquesModel("Nihilego", "Lanzamugre"),
new MejoresAtaquesModel("Ninetales", "Giro Fuego"),
new MejoresAtaquesModel("Ninetales", "Llamarada"),
new MejoresAtaquesModel("Ninetales", "Meteorobola Fuego"),
new MejoresAtaquesModel("Ninetales", "Sofoco"),
new MejoresAtaquesModel("Noivern", "Cometa Draco"),
new MejoresAtaquesModel("Noivern", "Mordisco"),
new MejoresAtaquesModel("Noivern", "Tajo Aéreo"),
new MejoresAtaquesModel("Noivern", "Vendaval"),
new MejoresAtaquesModel("Obstagoon", "Contraataque"),
new MejoresAtaquesModel("Obstagoon", "Hiperrayo"),
new MejoresAtaquesModel("Obstagoon", "Lanzamugre"),
new MejoresAtaquesModel("Octillery", "Lanzamugre"),
new MejoresAtaquesModel("Octillery", "Pistola Agua"),
new MejoresAtaquesModel("Oinkologne", "Abrecaminos"),
new MejoresAtaquesModel("Oinkologne", "Derribo"),
new MejoresAtaquesModel("Oinkologne", "Golpe Cuerpo"),
new MejoresAtaquesModel("Oinkologne", "Placaje"),
new MejoresAtaquesModel("Omastar", "Hidrobomba"),
new MejoresAtaquesModel("Omastar", "Lanzarrocas"),
new MejoresAtaquesModel("Oranguru", "Cabezazo Zen"),
new MejoresAtaquesModel("Oranguru", "Confusión"),
new MejoresAtaquesModel("Oranguru", "Premonición"),
new MejoresAtaquesModel("Oricorio", "Tajo Aéreo"),
new MejoresAtaquesModel("Oricorio", "Vendaval"),
new MejoresAtaquesModel("Palkia", "Cola Dragón"),
new MejoresAtaquesModel("Palkia", "Cometa Draco"),
new MejoresAtaquesModel("Palkia", "Dragoaliento"),
new MejoresAtaquesModel("Palkia", "Hidrobomba"),
new MejoresAtaquesModel("Passimian", "A Bocajarro"),
new MejoresAtaquesModel("Passimian", "Contraataque"),
new MejoresAtaquesModel("Pawmot", "A Bocajarro"),
new MejoresAtaquesModel("Pawmot", "Patada Baja"),
new MejoresAtaquesModel("Pheromosa", "A Bocajarro"),
new MejoresAtaquesModel("Pheromosa", "Onda Certera"),
new MejoresAtaquesModel("Pheromosa", "Patada Baja"),
new MejoresAtaquesModel("Pheromosa", "Picadura"),
new MejoresAtaquesModel("Piloswine", "Alud"),
new MejoresAtaquesModel("Piloswine", "Canto Helado"),
new MejoresAtaquesModel("Piloswine", "Roca Afilada"),
new MejoresAtaquesModel("Pinsir", "A Bocajarro"),
new MejoresAtaquesModel("Pinsir", "Golpe Roca"),
new MejoresAtaquesModel("Pinsir", "Picadura"),
new MejoresAtaquesModel("Politoed", "Burbuja"),
new MejoresAtaquesModel("Politoed", "Hidrobomba"),
new MejoresAtaquesModel("Politoed", "Meteorobola Agua"),
new MejoresAtaquesModel("Politoed", "Surf"),
new MejoresAtaquesModel("Poliwarth", "Burbuja"),
new MejoresAtaquesModel("Poliwarth", "Golpe Roca"),
new MejoresAtaquesModel("Poliwarth", "Hidrobomba"),
new MejoresAtaquesModel("Porygon-Z", "Hiperrayo"),
new MejoresAtaquesModel("Porygon-Z", "Poder Oculto"),
new MejoresAtaquesModel("Porygon-Z", "Ventisca"),
new MejoresAtaquesModel("Primarina", "Cascada"),
new MejoresAtaquesModel("Primarina", "Encanto"),
new MejoresAtaquesModel("Primarina", "Fuerza Lunar"),
new MejoresAtaquesModel("Primarina", "Hidrobomba"),
new MejoresAtaquesModel("Primeape", "A Bocajarro"),
new MejoresAtaquesModel("Primeape", "Contraataque"),
new MejoresAtaquesModel("Pyroar Hembra", "Colmillo Ígneo"),
new MejoresAtaquesModel("Pyroar Hembra", "Sofoco"),
new MejoresAtaquesModel("Pyroar macho", "Colmillo Ígneo"),
new MejoresAtaquesModel("Pyroar macho", "Sofoco"),
new MejoresAtaquesModel("Quaquaval", "A Bocajarro"),
new MejoresAtaquesModel("Quaquaval", "Pistola Agua"),
new MejoresAtaquesModel("Raikou", "Impactrueno"),
new MejoresAtaquesModel("Raikou", "Trueno"),
new MejoresAtaquesModel("Raikou", "Voltio Cruel"),
new MejoresAtaquesModel("Raikou", "Voltiocambio"),
new MejoresAtaquesModel("Rampardos", "Antiaéreo"),
new MejoresAtaquesModel("Rampardos", "Avalancha"),
new MejoresAtaquesModel("Rampardos", "Lanzallamas"),
new MejoresAtaquesModel("Rapidash", "Calcinación"),
new MejoresAtaquesModel("Rapidash", "Giro Fuego"),
new MejoresAtaquesModel("Rapidash", "Llamarada"),
new MejoresAtaquesModel("Rapidash", "Onda Ígnea"),
new MejoresAtaquesModel("Rayquaza", "Cola Dragón"),
new MejoresAtaquesModel("Rayquaza", "Enfado"),
new MejoresAtaquesModel("Rayquaza", "Vendaval"),
new MejoresAtaquesModel("Regice", "Golpe Roca"),
new MejoresAtaquesModel("Regice", "Vaho Gélido"),
new MejoresAtaquesModel("Regice", "Ventisca"),
new MejoresAtaquesModel("Regigigas", "Cabezazo Zen"),
new MejoresAtaquesModel("Regigigas", "Gigaimpacto"),
new MejoresAtaquesModel("Regigigas", "Golpe Roca"),
new MejoresAtaquesModel("Regigigas", "Poder Oculto"),
new MejoresAtaquesModel("Regirock", "Lanzarrocas"),
new MejoresAtaquesModel("Regirock", "Roca Afilada"),
new MejoresAtaquesModel("Reshiram", "Colmillo Ígneo"),
new MejoresAtaquesModel("Reshiram", "Cometa Draco"),
new MejoresAtaquesModel("Reshiram", "Dragoaliento"),
new MejoresAtaquesModel("Reshiram", "Sofoco"),
new MejoresAtaquesModel("Reuniclus", "Cabezazo Zen"),
new MejoresAtaquesModel("Reuniclus", "Premonición"),
new MejoresAtaquesModel("Rhydon", "Bofetón Lodo"),
new MejoresAtaquesModel("Rhydon", "Megacuerno"),
new MejoresAtaquesModel("Rhydon", "Roca Afilada"),
new MejoresAtaquesModel("Rhydon", "Terremoto"),
new MejoresAtaquesModel("Rhyperior", "Antiaéreo"),
new MejoresAtaquesModel("Rhyperior", "Bofetón Lodo"),
new MejoresAtaquesModel("Rhyperior", "Roca Afilada"),
new MejoresAtaquesModel("Rhyperior", "Terremoto"),
new MejoresAtaquesModel("Roserade", "Bomba Lodo"),
new MejoresAtaquesModel("Roserade", "Hierba Lazo"),
new MejoresAtaquesModel("Roserade", "Hoja Afilada"),
new MejoresAtaquesModel("Roserade", "Puya Nociva"),
new MejoresAtaquesModel("Roserade", "Rayo Solar"),
new MejoresAtaquesModel("Salamence", "Cola Dragón"),
new MejoresAtaquesModel("Salamence", "Cometa Draco"),
new MejoresAtaquesModel("Samurott", "Cascada"),
new MejoresAtaquesModel("Samurott", "Hidrobomba"),
new MejoresAtaquesModel("Samurott", "Megacuerno"),
new MejoresAtaquesModel("Sandslash Alola", "Garra Metal"),
new MejoresAtaquesModel("Sandslash Alola", "Ventisca"),
new MejoresAtaquesModel("Sandslash normal", "Disparo Lodo"),
new MejoresAtaquesModel("Sandslash normal", "Garra Metal"),
new MejoresAtaquesModel("Sandslash normal", "Terremoto"),
new MejoresAtaquesModel("Sawk", "Onda Certera"),
new MejoresAtaquesModel("Sawk", "Patada Baja"),
new MejoresAtaquesModel("Sawk", "Puya Nociva"),
new MejoresAtaquesModel("Sawsbuck - Spring", "Finta"),
new MejoresAtaquesModel("Sawsbuck - Spring", "Hiperrayo"),
new MejoresAtaquesModel("Sawsbuck - Spring", "Megacuerno"),
new MejoresAtaquesModel("Sawsbuck - Spring", "Rayo Solar"),
new MejoresAtaquesModel("Sawsbuck - Summer", "Finta"),
new MejoresAtaquesModel("Sawsbuck - Summer", "Hiperrayo"),
new MejoresAtaquesModel("Sawsbuck - Summer", "Megacuerno"),
new MejoresAtaquesModel("Sawsbuck - Summer", "Rayo Solar"),
new MejoresAtaquesModel("Sawsbuck - Winter", "Finta"),
new MejoresAtaquesModel("Sawsbuck - Winter", "Hiperrayo"),
new MejoresAtaquesModel("Sawsbuck - Winter", "Megacuerno"),
new MejoresAtaquesModel("Sawsbuck Autumm", "Finta"),
new MejoresAtaquesModel("Sawsbuck Autumm", "Hiperrayo"),
new MejoresAtaquesModel("Sawsbuck Autumm", "Megacuerno"),
new MejoresAtaquesModel("Sceptile", "Corte Furia"),
new MejoresAtaquesModel("Sceptile", "Hoja Aguda"),
new MejoresAtaquesModel("Sceptile", "Planta Feroz"),
new MejoresAtaquesModel("Sceptile", "Semilladora"),
new MejoresAtaquesModel("Sceptile", "Terremoto"),
new MejoresAtaquesModel("Scizor", "Cabeza de Hierro"),
new MejoresAtaquesModel("Scizor", "Puño Bala"),
new MejoresAtaquesModel("Scizor", "Tijera X"),
new MejoresAtaquesModel("Scolipede", "Megacuerno"),
new MejoresAtaquesModel("Scolipede", "Puya Nociva"),
new MejoresAtaquesModel("Scrafty", "Contraataque"),
new MejoresAtaquesModel("Scrafty", "Juego Sucio"),
new MejoresAtaquesModel("Scyther", "Ala de Acero"),
new MejoresAtaquesModel("Scyther", "Tajo Aéreo"),
new MejoresAtaquesModel("Scyther", "Tijera X"),
new MejoresAtaquesModel("Scyther", "Zumbido"),
new MejoresAtaquesModel("Seaking", "Cascada"),
new MejoresAtaquesModel("Seaking", "Megacuerno"),
new MejoresAtaquesModel("Seismitoad", "Bomba Lodo"),
new MejoresAtaquesModel("Seismitoad", "Burbuja"),
new MejoresAtaquesModel("Seismitoad", "Tierra Viva"),
new MejoresAtaquesModel("Serperior", "Cola Férrea"),
new MejoresAtaquesModel("Serperior", "Hierba Lazo"),
new MejoresAtaquesModel("Serperior", "Látigo Cepa"),
new MejoresAtaquesModel("Shiftry", "Hoja Afilada"),
new MejoresAtaquesModel("Shiftry", "Juego Sucio"),
new MejoresAtaquesModel("Shiftry", "Vendaval"),
new MejoresAtaquesModel("Sigilyph", "Aire Afilado"),
new MejoresAtaquesModel("Sigilyph", "Cabezazo Zen"),
new MejoresAtaquesModel("Sigilyph", "Doble Rayo"),
new MejoresAtaquesModel("Sigilyph", "Psicorrayo"),
new MejoresAtaquesModel("Sigilyph", "Tajo Aéreo"),
new MejoresAtaquesModel("Simisear", "Giro Fuego"),
new MejoresAtaquesModel("Simisear", "Lanzallamas"),
new MejoresAtaquesModel("Simisear", "Llamarada"),
new MejoresAtaquesModel("Sirfetch'd", "A Bocajarro"),
new MejoresAtaquesModel("Sirfetch'd", "Contraataque"),
new MejoresAtaquesModel("Sirfetch'd", "Pájaro Osado"),
new MejoresAtaquesModel("Skeledirge", "Bola Sombra"),
new MejoresAtaquesModel("Skeledirge", "Calcinación"),
new MejoresAtaquesModel("Skeledirge", "Lanzallamas"),
new MejoresAtaquesModel("Skeledirge", "Mordisco"),
new MejoresAtaquesModel("Skutank", "Bomba Lodo"),
new MejoresAtaquesModel("Skutank", "Mordisco"),
new MejoresAtaquesModel("Skutank", "Puya Nociva"),
new MejoresAtaquesModel("Slaking", "Bostezo"),
new MejoresAtaquesModel("Slaking", "Hiperrayo"),
new MejoresAtaquesModel("Slowbro", "Confusión"),
new MejoresAtaquesModel("Slowbro", "Psíquico"),
new MejoresAtaquesModel("Slowking", "Confusión"),
new MejoresAtaquesModel("Slowking", "Psíquico"),
new MejoresAtaquesModel("Slowking", "Ventisca"),
new MejoresAtaquesModel("Snorlax", "Cabezazo"),
new MejoresAtaquesModel("Snorlax", "Cabezazo Zen"),
new MejoresAtaquesModel("Snorlax", "Hiperrayo"),
new MejoresAtaquesModel("Snorlax", "Lengüetazo"),
new MejoresAtaquesModel("Solrock", "Avalancha"),
new MejoresAtaquesModel("Solrock", "Confusión"),
new MejoresAtaquesModel("Solrock", "Lanzarrocas"),
new MejoresAtaquesModel("Solrock", "Psíquico"),
new MejoresAtaquesModel("Solrock", "Rayo Solar"),
new MejoresAtaquesModel("Staraptor", "A Bocajarro"),
new MejoresAtaquesModel("Staraptor", "Ataque Ala"),
new MejoresAtaquesModel("Staraptor", "Ataque Rápido"),
new MejoresAtaquesModel("Staraptor", "Pájaro Osado"),
new MejoresAtaquesModel("Starmie", "Hidrobomba"),
new MejoresAtaquesModel("Starmie", "Pistola Agua"),
new MejoresAtaquesModel("Steelix", "Cola Férrea"),
new MejoresAtaquesModel("Steelix", "Cuerpo Pesado"),
new MejoresAtaquesModel("Steelix", "Terremoto"),
new MejoresAtaquesModel("Stoutland", "Carantoña"),
new MejoresAtaquesModel("Stoutland", "Lengüetazo"),
new MejoresAtaquesModel("Stoutland", "Voltio Cruel"),
new MejoresAtaquesModel("Suicune", "Alarido"),
new MejoresAtaquesModel("Suicune", "Hidrobomba"),
new MejoresAtaquesModel("Suicune", "Paranormal"),
new MejoresAtaquesModel("Suicune", "Poder Oculto"),
new MejoresAtaquesModel("Swampert", "Hidrocañón"),
new MejoresAtaquesModel("Swampert", "Pistola Agua"),
new MejoresAtaquesModel("Swampert", "Surf"),
new MejoresAtaquesModel("Swampert", "Terremoto"),
new MejoresAtaquesModel("Talonflame", "Ala de Acero"),
new MejoresAtaquesModel("Talonflame", "Giro Fuego"),
new MejoresAtaquesModel("Talonflame", "Pájaro Osado"),
new MejoresAtaquesModel("Tangrowth", "Latigazo"),
new MejoresAtaquesModel("Tangrowth", "Látigo Cepa"),
new MejoresAtaquesModel("Tangrowth", "Rayo Solar"),
new MejoresAtaquesModel("Tapu Bulu", "Combate"),
new MejoresAtaquesModel("Tapu Bulu", "Golpe Roca"),
new MejoresAtaquesModel("Tapu Bulu", "Megacuerno"),
new MejoresAtaquesModel("Tapu Bulu", "Rayo Solar"),
new MejoresAtaquesModel("Tapu Koko", "Ataque Rápido"),
new MejoresAtaquesModel("Tapu Koko", "Pájaro Osado"),
new MejoresAtaquesModel("Tapu Koko", "Trueno"),
new MejoresAtaquesModel("Tapu Koko", "Voltiocambio"),
new MejoresAtaquesModel("Tapu Lele", "Combate"),
new MejoresAtaquesModel("Tapu Lele", "Confusión"),
new MejoresAtaquesModel("Tapu Lele", "Premonición"),
new MejoresAtaquesModel("Tauros", "Placaje"),
new MejoresAtaquesModel("Tauros", "Terremoto"),
new MejoresAtaquesModel("Tentacruel", "Ácido"),
new MejoresAtaquesModel("Tentacruel", "Hidrobomba"),
new MejoresAtaquesModel("Tentacruel", "Onda Tóxica"),
new MejoresAtaquesModel("Tentacruel", "Puya Nociva"),
new MejoresAtaquesModel("Tentacruel", "Ventisca"),
new MejoresAtaquesModel("Terrakion", "A Bocajarro"),
new MejoresAtaquesModel("Terrakion", "Antiaéreo"),
new MejoresAtaquesModel("Throh", "Onda Certera"),
new MejoresAtaquesModel("Throh", "Patada Baja"),
new MejoresAtaquesModel("Thundurus", "Impactrueno"),
new MejoresAtaquesModel("Thundurus", "Trueno"),
new MejoresAtaquesModel("Thundurus Incarnate", "Impactrueno"),
new MejoresAtaquesModel("Thundurus Incarnate", "Trueno"),
new MejoresAtaquesModel("Thundurus Tótem - Therian", "Impactrueno"),
new MejoresAtaquesModel("Thundurus Tótem - Therian", "Trueno"),
new MejoresAtaquesModel("Togekiss", "Brillo Mágico"),
new MejoresAtaquesModel("Togekiss", "Encanto"),
new MejoresAtaquesModel("Togekiss", "Lanzallamas"),
new MejoresAtaquesModel("Togekiss", "Tajo Aéreo"),
new MejoresAtaquesModel("Tornadus", "Mordisco"),
new MejoresAtaquesModel("Tornadus", "Tajo Aéreo"),
new MejoresAtaquesModel("Tornadus", "Tornado"),
new MejoresAtaquesModel("Tornadus", "Vendaval"),
new MejoresAtaquesModel("Torterra", "Hoja Afilada"),
new MejoresAtaquesModel("Torterra", "Planta Feroz"),
new MejoresAtaquesModel("Torterra", "Rayo Solar"),
new MejoresAtaquesModel("Torterra", "Roca Afilada"),
new MejoresAtaquesModel("Torterra", "Terremoto"),
new MejoresAtaquesModel("Toucannon", "Foco Resplandor"),
new MejoresAtaquesModel("Toucannon", "Golpe Roca"),
new MejoresAtaquesModel("Toucannon", "Pico Taladro"),
new MejoresAtaquesModel("Toucannon", "Picotazo"),
new MejoresAtaquesModel("Toxicroak", "Bomba Lodo"),
new MejoresAtaquesModel("Toxicroak", "Contraataque"),
new MejoresAtaquesModel("Toxicroak", "Puño Dinámico"),
new MejoresAtaquesModel("Toxicroak", "Puya Nociva"),
new MejoresAtaquesModel("Trevenant", "Bola Sombra"),
new MejoresAtaquesModel("Trevenant", "Garra Umbría"),
new MejoresAtaquesModel("Typhlosion", "Calcinación"),
new MejoresAtaquesModel("Typhlosion", "Sofoco"),
new MejoresAtaquesModel("Tyranitar", "Antiaéreo"),
new MejoresAtaquesModel("Tyranitar", "Cola Férrea"),
new MejoresAtaquesModel("Tyranitar", "Mordisco"),
new MejoresAtaquesModel("Tyranitar", "Roca Afilada"),
new MejoresAtaquesModel("Unfezant", "Ala de Acero"),
new MejoresAtaquesModel("Unfezant", "Ataque Aéreo"),
new MejoresAtaquesModel("Unfezant", "Hiperrayo"),
new MejoresAtaquesModel("Unfezant", "Tajo Aéreo"),
new MejoresAtaquesModel("Ursaluna", "Golpe Aéreo"),
new MejoresAtaquesModel("Ursaluna", "Golpe Roca"),
new MejoresAtaquesModel("Ursaluna", "Placaje"),
new MejoresAtaquesModel("Ursaluna", "Puño Fuego"),
new MejoresAtaquesModel("Ursaluna", "Puño Trueno"),
new MejoresAtaquesModel("Ursaring", "A Bocajarro"),
new MejoresAtaquesModel("Ursaring", "Contraataque"),
new MejoresAtaquesModel("Ursaring", "Garra Metal"),
new MejoresAtaquesModel("Ursaring", "Garra Umbría"),
new MejoresAtaquesModel("Ursaring", "Hiperrayo"),
new MejoresAtaquesModel("Vanilluxe", "Vaho Gélido"),
new MejoresAtaquesModel("Vanilluxe", "Ventisca"),
new MejoresAtaquesModel("Vaporeon", "Hidroariete"),
new MejoresAtaquesModel("Vaporeon", "Hidrobomba"),
new MejoresAtaquesModel("Vaporeon", "Pistola Agua"),
new MejoresAtaquesModel("Venusaur", "Hoja Afilada"),
new MejoresAtaquesModel("Venusaur", "Látigo Cepa"),
new MejoresAtaquesModel("Venusaur", "Planta Feroz"),
new MejoresAtaquesModel("Venusaur", "Tormenta Floral"),
new MejoresAtaquesModel("Victini", "Confusión"),
new MejoresAtaquesModel("Victini", "Sofoco"),
new MejoresAtaquesModel("Victreebel", "Ácido"),
new MejoresAtaquesModel("Victreebel", "Bomba Lodo"),
new MejoresAtaquesModel("Victreebel", "Hoja Afilada"),
new MejoresAtaquesModel("Victreebel", "Rayo Solar"),
new MejoresAtaquesModel("Vikavolt", "Bofetón Lodo"),
new MejoresAtaquesModel("Vikavolt", "Chispazo"),
new MejoresAtaquesModel("Vikavolt", "Picadura"),
new MejoresAtaquesModel("Vikavolt", "Tijera X"),
new MejoresAtaquesModel("Vileplume", "Hoja Afilada"),
new MejoresAtaquesModel("Vileplume", "Rayo Solar"),
new MejoresAtaquesModel("Vileplume", "Tormenta Floral"),
new MejoresAtaquesModel("Virizion", "A Bocajarro"),
new MejoresAtaquesModel("Virizion", "Ataque Rápido"),
new MejoresAtaquesModel("Virizion", "Cabezazo Zen"),
new MejoresAtaquesModel("Wailord", "Pistola Agua"),
new MejoresAtaquesModel("Wailord", "Surf"),
new MejoresAtaquesModel("Wailord", "Ventisca"),
new MejoresAtaquesModel("Walrein", "Cascada"),
new MejoresAtaquesModel("Walrein", "Ventisca"),
new MejoresAtaquesModel("Weavile", "Alarido"),
new MejoresAtaquesModel("Weavile", "Alud"),
new MejoresAtaquesModel("Weavile", "Canto Helado"),
new MejoresAtaquesModel("Weavile", "Finta"),
new MejoresAtaquesModel("Weavile", "Juego Sucio"),
new MejoresAtaquesModel("Weavile", "Onda Certera"),
new MejoresAtaquesModel("Weezing", "Acoso"),
new MejoresAtaquesModel("Weezing", "Bomba Lodo"),
new MejoresAtaquesModel("Weezing", "Placaje"),
new MejoresAtaquesModel("Wyrdeer", "Cabezazo Zen"),
new MejoresAtaquesModel("Wyrdeer", "Confusión"),
new MejoresAtaquesModel("Wyrdeer", "Megacuerno"),
new MejoresAtaquesModel("Wyrdeer", "Pisotón"),
new MejoresAtaquesModel("Wyrdeer", "Placaje"),
new MejoresAtaquesModel("Wyrdeer", "Psíquico"),
new MejoresAtaquesModel("Xatu", "Premonición"),
new MejoresAtaquesModel("Xatu", "Tajo Aéreo"),
new MejoresAtaquesModel("Xerneas", "A Bocajarro"),
new MejoresAtaquesModel("Xerneas", "Cabezazo Zen"),
new MejoresAtaquesModel("Xerneas", "Megacuerno"),
new MejoresAtaquesModel("Xerneas", "Placaje"),
new MejoresAtaquesModel("Xurkitree", "Chispa"),
new MejoresAtaquesModel("Xurkitree", "Impactrueno"),
new MejoresAtaquesModel("Xurkitree", "Trueno"),
new MejoresAtaquesModel("Yanmega", "Ataque Ala"),
new MejoresAtaquesModel("Yanmega", "Golpe Aéreo"),
new MejoresAtaquesModel("Yanmega", "Picadura"),
new MejoresAtaquesModel("Yanmega", "Zumbido"),
new MejoresAtaquesModel("Yveltal", "Alarido"),
new MejoresAtaquesModel("Yveltal", "Tornado"),
new MejoresAtaquesModel("Yveltal", "Vendaval"),
new MejoresAtaquesModel("Zacian", "A Bocajarro"),
new MejoresAtaquesModel("Zacian", "Colmillo Ígneo"),
new MejoresAtaquesModel("Zacian", "Garra Metal"),
new MejoresAtaquesModel("Zamazenta", "A Bocajarro"),
new MejoresAtaquesModel("Zamazenta", "Alarido"),
new MejoresAtaquesModel("Zamazenta", "Ataque Rápido"),
new MejoresAtaquesModel("Zamazenta", "Garra Metal"),
new MejoresAtaquesModel("Zangoose", "A Bocajarro"),
new MejoresAtaquesModel("Zangoose", "Garra Umbría"),
new MejoresAtaquesModel("Zapdos", "Electrocañón"),
new MejoresAtaquesModel("Zapdos", "Impactrueno"),
new MejoresAtaquesModel("Zapdos", "Rayo Carga"),
new MejoresAtaquesModel("Zapdos", "Trueno"),
new MejoresAtaquesModel("Zarude", "Latigazo"),
new MejoresAtaquesModel("Zarude", "Látigo Cepa"),
new MejoresAtaquesModel("Zarude", "Mordisco"),
new MejoresAtaquesModel("Zekrom", "Dragoaliento"),
new MejoresAtaquesModel("Zekrom", "Voltio Cruel"),
new MejoresAtaquesModel("Rillaboom", "Hoja afilada"),
new MejoresAtaquesModel("Rillaboom", "Hierba Lazo"),
new MejoresAtaquesModel("Arcanine Hisuian", "Colmillo Ígneo"),
new MejoresAtaquesModel("Arcanine Hisuian", "Lanzallamas"),
new MejoresAtaquesModel("Arcanine Hisuian", "Avalancha"),
new MejoresAtaquesModel("Cinderace", "Ascuas"),
new MejoresAtaquesModel("Cinderace", "Onda certera"),
new MejoresAtaquesModel("Cinderace", "Lanzallamas"),
new MejoresAtaquesModel("Inteleon", "Destructor"),
new MejoresAtaquesModel("Inteleon", "Pistola Agua"),
new MejoresAtaquesModel("Inteleon", "Surf"),
new MejoresAtaquesModel("Kommo-o", "Cola Dragón"),
new MejoresAtaquesModel("Kommo-o", "A bocajarro"),
new MejoresAtaquesModel("Rapidash - Galarian", "patada baja"),
new MejoresAtaquesModel("Rapidash - Galarian", "Psicocorte"),
new MejoresAtaquesModel("Rapidash - Galarian", "Viento Feérico"),
new MejoresAtaquesModel("Rapidash - Galarian", "Fuerza equina"),
new MejoresAtaquesModel("Komala", "Desenrrollar"),
new MejoresAtaquesModel("Komala", "Vendetta"),
new MejoresAtaquesModel("Dragapult", "Cola Dragón"),
new MejoresAtaquesModel("Dragapult", "Vasto impacto"),
new MejoresAtaquesModel("Goodra", "Dragoaliento"),
new MejoresAtaquesModel("Goodra", "Cometa draco"),
new MejoresAtaquesModel("Ho-oh", "Calcinación"),
new MejoresAtaquesModel("Ho-oh", "Ala de acero"),
new MejoresAtaquesModel("Ho-oh", "Pájaro osado"),
new MejoresAtaquesModel("Overqwil", "Puya nociva"),
new MejoresAtaquesModel("Overqwil", "Bomba lodo"),
new MejoresAtaquesModel("Darmanitan de Galar", "Placaje"),
new MejoresAtaquesModel("Darmanitan de Galar", "Colmillo Hielo"),
new MejoresAtaquesModel("Cetitan", "Canto helado"),
new MejoresAtaquesModel("Cetitan", "Alud"),
new MejoresAtaquesModel("Tsareena", "HOJA AFILADA"),
new MejoresAtaquesModel("Tsareena", "Hierba lazo"),
new MejoresAtaquesModel("Tyrunt", "Cola Dragón"),
new MejoresAtaquesModel("Tyrunt", "Garra Dragón"),
new MejoresAtaquesModel("Tyrunt", "Pisotón"),
new MejoresAtaquesModel("Luxray", "Alarido"),
new MejoresAtaquesModel("Luxray", "Chispa"),
new MejoresAtaquesModel("Luxray", "Poder oculto"),
new MejoresAtaquesModel("Luxray", "Voltio cruel"),
new MejoresAtaquesModel("Luxray", "Hiperrayo"),
new MejoresAtaquesModel("Aurorus", "Lanzarrocas"),
new MejoresAtaquesModel("Aurorus", "Vaho Gélido"),
new MejoresAtaquesModel("Aurorus", "Rayo meteórico"),
new MejoresAtaquesModel("Durant", "Garra metal"),
new MejoresAtaquesModel("Durant", "Roca afilada"),
new MejoresAtaquesModel("Zoroark", "Alarido"),
new MejoresAtaquesModel("Zoroark", "Garra Umbría"),
new MejoresAtaquesModel("Zoroark", "Juego sucio"),
new MejoresAtaquesModel("Lunatone", "Lanzarrocas"),
new MejoresAtaquesModel("Lunatone", "Confusión"),
new MejoresAtaquesModel("Lunatone", "Psíquico"),
new MejoresAtaquesModel("Lunatone", "Avalancha"),
new MejoresAtaquesModel("Camerupt", "Calcinación"),
new MejoresAtaquesModel("Camerupt", "Sofoco"),
new MejoresAtaquesModel("Camerupt", "Terremoto"),
new MejoresAtaquesModel("Sneasler", "Puya nociva"),
new MejoresAtaquesModel("Sneasler", "Golpe roca"),
new MejoresAtaquesModel("Sneasler", "a Bocajarro"),
new MejoresAtaquesModel("Palossand", "Disparo Lodo"),
new MejoresAtaquesModel("Palossand", "Bola sombra"),
new MejoresAtaquesModel("Palossand", "Arenas ardientes"),
new MejoresAtaquesModel("Palossand", "Ataque arena"),
new MejoresAtaquesModel("Malamar", "Picotazo"),
new MejoresAtaquesModel("Malamar", "Psicocorte"),
new MejoresAtaquesModel("Malamar", "Psicoonda"),
new MejoresAtaquesModel("Malamar", "Juego sucio"),
new MejoresAtaquesModel("Malamar", "Hiperrayo"),
new MejoresAtaquesModel("Florges - White", "Hoja afilada"),
new MejoresAtaquesModel("Florges - White", "Látigo cepa"),
new MejoresAtaquesModel("Florges - White", "Tormenta floral"),
new MejoresAtaquesModel("Tapu Bulu", "Furia Natural"),
new MejoresAtaquesModel("Hatterene", "Encanto"),
new MejoresAtaquesModel("Hatterene", "Confusión"),
new MejoresAtaquesModel("Hatterene", "Psíquico"),
new MejoresAtaquesModel("Hatterene", "Latigazo"),
new MejoresAtaquesModel("Magmar", "Ascuas"),
new MejoresAtaquesModel("Magmar", "Llamarada"),
new MejoresAtaquesModel("Magmar", "Lanzallamas"),
new MejoresAtaquesModel("Tornadus forma avatar", "Tajo aéreo"),
new MejoresAtaquesModel("Tornadus forma avatar", "Vendaval"),
new MejoresAtaquesModel("Dudunsparce (Forma Binodular)", "Mordisco"),
new MejoresAtaquesModel("Dudunsparce (Forma Binodular)", "Avalancha"),
new MejoresAtaquesModel("Dudunsparce (Forma Binodular)", "Taladradora"),
new MejoresAtaquesModel("Milotic", "Cascada"),
new MejoresAtaquesModel("Milotic", "Cola Dragón"),
new MejoresAtaquesModel("Milotic", "Surf"),
new MejoresAtaquesModel("Milotic", "Ventisca"),
new MejoresAtaquesModel("Zoroark - Blanco", "Alarido"),
new MejoresAtaquesModel("Zoroark - Blanco", "Garra Umbría"),
new MejoresAtaquesModel("Zoroark - Blanco", "Juego sucio")

    ];

constructor() {
}
}