import { PokemonModel } from './zzzpokemon.model';

export class PokemonIniciales {

pokemonIniciales: PokemonModel[] = [
    new PokemonModel("Abomasnow"),
new PokemonModel("Absol"),
new PokemonModel("Accelgor"),
new PokemonModel("Aerodactyl"),
new PokemonModel("Aggron"),
new PokemonModel("Alakazam"),
new PokemonModel("Ambipom"),
new PokemonModel("Amoonguss"),
new PokemonModel("Ampharos"),
new PokemonModel("Annihilape"),
new PokemonModel("Arboliva"),
new PokemonModel("Arcanine"),
new PokemonModel("Arcanine Hisuian"),
new PokemonModel("Archeops"),
new PokemonModel("Armaldo"),
new PokemonModel("Aromatisse"),
new PokemonModel("Articuno"),
new PokemonModel("Aurorus"),
new PokemonModel("Avalugg"),
new PokemonModel("Banette"),
new PokemonModel("Barbaracle"),
new PokemonModel("Baxcalibur"),
new PokemonModel("Beartic"),
new PokemonModel("Beheeyem"),
new PokemonModel("Bellibol"),
new PokemonModel("Bewear"),
new PokemonModel("Blastoise"),
new PokemonModel("Blaziken"),
new PokemonModel("Blissey"),
new PokemonModel("Braviary"),
new PokemonModel("Breloom"),
new PokemonModel("Buzzwole"),
new PokemonModel("Cacturne"),
new PokemonModel("Camerupt"),
new PokemonModel("Cetitan"),
new PokemonModel("Chandelure"),
new PokemonModel("Charizard"),
new PokemonModel("Chesnaught"),
new PokemonModel("Cinccino"),
new PokemonModel("Cinderace"),
new PokemonModel("Clawitzer"),
new PokemonModel("Clefable"),
new PokemonModel("Cloyster"),
new PokemonModel("Conkeldurr"),
new PokemonModel("Crabominable"),
new PokemonModel("Cradily"),
new PokemonModel("Crawdaunt"),
new PokemonModel("Cresselia"),
new PokemonModel("Crobat"),
new PokemonModel("Crustle"),
new PokemonModel("Cryogonal"),
new PokemonModel("Darkrai"),
new PokemonModel("Darmanitan - Standard"),
new PokemonModel("Darmanitan de Galar"),
new PokemonModel("Decidueye"),
new PokemonModel("Decidueye - Hisui"),
new PokemonModel("Delphox"),
new PokemonModel("Dialga"),
new PokemonModel("Dialga Hisui"),
new PokemonModel("Dodrio"),
new PokemonModel("Donphan"),
new PokemonModel("Dragalge"),
new PokemonModel("Dragapult"),
new PokemonModel("Dragonite"),
new PokemonModel("Drapion"),
new PokemonModel("Drifblim"),
new PokemonModel("Dudunsparce (Forma Binodular)"),
new PokemonModel("Durant"),
new PokemonModel("Dusknoir"),
new PokemonModel("Eelektross"),
new PokemonModel("Electivire"),
new PokemonModel("Electrode Hisuain"),
new PokemonModel("Emboar"),
new PokemonModel("Empoleon"),
new PokemonModel("Enamorus Avatar"),
new PokemonModel("Entei"),
new PokemonModel("Escavalier"),
new PokemonModel("Espeon"),
new PokemonModel("Excadrill"),
new PokemonModel("Exeggutor Alola"),
new PokemonModel("Exeggutor normal"),
new PokemonModel("Exploud"),
new PokemonModel("Feraligatr"),
new PokemonModel("Flareon"),
new PokemonModel("Floatzel"),
new PokemonModel("Florges - Blue"),
new PokemonModel("Florges - Orange"),
new PokemonModel("Florges - Red"),
new PokemonModel("Florges - White"),
new PokemonModel("Florges . Yellow"),
new PokemonModel("Flygon"),
new PokemonModel("Forretress"),
new PokemonModel("Gallade"),
new PokemonModel("Garbodor"),
new PokemonModel("Garchomp"),
new PokemonModel("Gardevoir"),
new PokemonModel("Gastrodom"),
new PokemonModel("Genesect"),
new PokemonModel("Gengar"),
new PokemonModel("Gigalith"),
new PokemonModel("Giratina Altered"),
new PokemonModel("Giratina Origen"),
new PokemonModel("Glaceon"),
new PokemonModel("Gliscor"),
new PokemonModel("Golduck"),
new PokemonModel("Golem Alola"),
new PokemonModel("Golem Normal"),
new PokemonModel("Golisopod"),
new PokemonModel("Golurk"),
new PokemonModel("Goodra"),
new PokemonModel("Gothielle"),
new PokemonModel("Gourgeist"),
new PokemonModel("Granbull"),
new PokemonModel("Greninja"),
new PokemonModel("Groudon"),
new PokemonModel("Grumpig"),
new PokemonModel("Gumshoos"),
new PokemonModel("Gyarados"),
new PokemonModel("Hariyama"),
new PokemonModel("Hatterene"),
new PokemonModel("Haxorus"),
new PokemonModel("Heatmor"),
new PokemonModel("Heatran"),
new PokemonModel("Heliolisk"),
new PokemonModel("Heracross"),
new PokemonModel("Hippodown"),
new PokemonModel("Hitmonchan"),
new PokemonModel("Hitmonlee"),
new PokemonModel("Honchkrow"),
new PokemonModel("Ho-oh"),
new PokemonModel("Houndoom"),
new PokemonModel("Hydreigon"),
new PokemonModel("Incineroar"),
new PokemonModel("Infernape"),
new PokemonModel("Inteleon"),
new PokemonModel("Jolteon"),
new PokemonModel("Jynx"),
new PokemonModel("Kabutops"),
new PokemonModel("Kangaskhan"),
new PokemonModel("Kingdra"),
new PokemonModel("Kingler"),
new PokemonModel("Komala"),
new PokemonModel("Kommo-o"),
new PokemonModel("Kyogre"),
new PokemonModel("Kyurem"),
new PokemonModel("Landorus"),
new PokemonModel("Landorus Therian"),
new PokemonModel("Lapras"),
new PokemonModel("Latias"),
new PokemonModel("Latios"),
new PokemonModel("Leafeon"),
new PokemonModel("Lickilicky"),
new PokemonModel("Lilligant"),
new PokemonModel("Ludicolo"),
new PokemonModel("Lugia"),
new PokemonModel("Lunatone"),
new PokemonModel("Luxray"),
new PokemonModel("Lycanroc Midday"),
new PokemonModel("Machamp"),
new PokemonModel("Magmar"),
new PokemonModel("Magmortar"),
new PokemonModel("Magnezone"),
new PokemonModel("Malamar"),
new PokemonModel("Mamoswine"),
new PokemonModel("Manectric"),
new PokemonModel("Masquerain"),
new PokemonModel("Meganium"),
new PokemonModel("Melmeltan"),
new PokemonModel("Meowscarada"),
new PokemonModel("Metagross"),
new PokemonModel("Mewtwo"),
new PokemonModel("Milotic"),
new PokemonModel("Miltank"),
new PokemonModel("Mismagius"),
new PokemonModel("Moltres"),
new PokemonModel("Mr.Mime"),
new PokemonModel("Muk Alola"),
new PokemonModel("Muk Normal"),
new PokemonModel("Munna"),
new PokemonModel("Musharna"),
new PokemonModel("Nidoking"),
new PokemonModel("Nidoqueen"),
new PokemonModel("Nihilego"),
new PokemonModel("Ninetales"),
new PokemonModel("Noivern"),
new PokemonModel("Obstagoon"),
new PokemonModel("Octillery"),
new PokemonModel("Oinkologne"),
new PokemonModel("Omastar"),
new PokemonModel("Oranguru"),
new PokemonModel("Oricorio"),
new PokemonModel("Overqwil"),
new PokemonModel("Palkia"),
new PokemonModel("Palkia Hisui"),
new PokemonModel("Palosand"),
new PokemonModel("Passimian"),
new PokemonModel("Pawmot"),
new PokemonModel("Pheromosa"),
new PokemonModel("Piloswine"),
new PokemonModel("Pinsir"),
new PokemonModel("Politoed"),
new PokemonModel("Poliwarth"),
new PokemonModel("Polteageist"),
new PokemonModel("Porygon-Z"),
new PokemonModel("Primarina"),
new PokemonModel("Primeape"),
new PokemonModel("Pyroar Hembra"),
new PokemonModel("Pyroar macho"),
new PokemonModel("Quaquaval"),
new PokemonModel("Raikou"),
new PokemonModel("Rampardos"),
new PokemonModel("Rapidash"),
new PokemonModel("Rapidash - Galarian"),
new PokemonModel("Rayquaza"),
new PokemonModel("Regice"),
new PokemonModel("Regigigas"),
new PokemonModel("Regirock"),
new PokemonModel("Reshiram"),
new PokemonModel("Reuniclus"),
new PokemonModel("Rhydon"),
new PokemonModel("Rhyperior"),
new PokemonModel("Rillaboom"),
new PokemonModel("Roserade"),
new PokemonModel("Salamence"),
new PokemonModel("Samurott"),
new PokemonModel("Sandslash Alola"),
new PokemonModel("Sandslash normal"),
new PokemonModel("Sawk"),
new PokemonModel("Sawsbuck - Spring"),
new PokemonModel("Sawsbuck - Summer"),
new PokemonModel("Sawsbuck - Winter"),
new PokemonModel("Sawsbuck Autumm"),
new PokemonModel("Sceptile"),
new PokemonModel("Scizor"),
new PokemonModel("Scolipede"),
new PokemonModel("Scrafty"),
new PokemonModel("Scyther"),
new PokemonModel("Seaking"),
new PokemonModel("Seismitoad"),
new PokemonModel("Serperior"),
new PokemonModel("Shiftry"),
new PokemonModel("Sigilyph"),
new PokemonModel("Simisear"),
new PokemonModel("Sirfetch'd"),
new PokemonModel("Skeledirge"),
new PokemonModel("Skutank"),
new PokemonModel("Slaking"),
new PokemonModel("Slowbro"),
new PokemonModel("Slowking"),
new PokemonModel("Sneasler"),
new PokemonModel("Snorlax"),
new PokemonModel("Solrock"),
new PokemonModel("Staraptor"),
new PokemonModel("Starmie"),
new PokemonModel("Steelix"),
new PokemonModel("Stoutland"),
new PokemonModel("Suicune"),
new PokemonModel("Swampert"),
new PokemonModel("Talonflame"),
new PokemonModel("Tangrowth"),
new PokemonModel("Tapu Bulu"),
new PokemonModel("Tapu Koko"),
new PokemonModel("Tapu Lele"),
new PokemonModel("Tauros"),
new PokemonModel("Tentacruel"),
new PokemonModel("Terrakion"),
new PokemonModel("Throh"),
new PokemonModel("Thundurus"),
new PokemonModel("Thundurus Incarnate"),
new PokemonModel("Thundurus Tótem - Therian"),
new PokemonModel("Togekiss"),
new PokemonModel("Tornadus forma avatar"),
new PokemonModel("Torterra"),
new PokemonModel("Toucannon"),
new PokemonModel("Toxicroak"),
new PokemonModel("Trevenant"),
new PokemonModel("Tsareena"),
new PokemonModel("Typhlosion"),
new PokemonModel("Typhlosion Hisui"),
new PokemonModel("Tyranitar"),
new PokemonModel("Tyrantrum"),
new PokemonModel("Tyrunt"),
new PokemonModel("Unfezant"),
new PokemonModel("Ursaluna"),
new PokemonModel("Ursaring"),
new PokemonModel("Vanilluxe"),
new PokemonModel("Vaporeon"),
new PokemonModel("Venusaur"),
new PokemonModel("Victini"),
new PokemonModel("Victreebel"),
new PokemonModel("Vikavolt"),
new PokemonModel("Vileplume"),
new PokemonModel("Virizion"),
new PokemonModel("Wailord"),
new PokemonModel("Wairein"),
new PokemonModel("Walrein"),
new PokemonModel("Weavile"),
new PokemonModel("Weezing"),
new PokemonModel("Wyrdeer"),
new PokemonModel("Xatu"),
new PokemonModel("Xerneas"),
new PokemonModel("Xurkitree"),
new PokemonModel("Yanmega"),
new PokemonModel("Yveltal"),
new PokemonModel("Zacian"),
new PokemonModel("Zamazenta"),
new PokemonModel("Zangoose"),
new PokemonModel("Zapdos"),
new PokemonModel("Zarude"),
new PokemonModel("Zekrom"),
new PokemonModel("Zoroark"),
new PokemonModel("Zoroark - Blanco")

];

constructor() {
}
}