docRef = await addDoc(this.productosCollectionRef, new Producto(1,"Azúcar Moreno",17,1,,,,"Azucarera");
docRef = await addDoc(this.productosCollectionRef, new Producto(2,"pan",4,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(3,"Nata",17,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(4,"Mantequilla",25,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(5,"Zanahorias",10,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(6,"Soja",20,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(7,"Trigo",2,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(8,"Tortitas",25,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(9,"Galleta",51,2,,,,"Panadería"
docRef = await addDoc(this.productosCollectionRef, new Producto(10,"Bacon",240,9,,"S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(11,"Huevos",20,9,,"S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(12,"Azúcar blanco",34,0,,,,"Azucarera"
docRef = await addDoc(this.productosCollectionRef, new Producto(13,"Añil",120,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(14,"maíz",5,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(15,"Palomitas",25,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(16,"Queso",51,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(17,"Caña de Azúcar",30,9,"SILO","S",9,"Azucarera"
docRef = await addDoc(this.productosCollectionRef, new Producto(18,"Leche",60,9,,"S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(19,"Tarta de Zanahoria",51,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(20,"Huevos con bacon",51,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(22,"Manzana",840,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(23,"Calabaza",5,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(24,"Pan de maíz",25,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(25,"Lana",420,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(26,"Tarta de calabaza",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(27,"Jersey",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(28,"Hamburguesa",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(29,"Tarta de Bacon",153,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(30,"Jersey azul",153,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(32,"Gorro azul de lana",51,4,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(33,"Almíbar",76,0,,,,"Azucarera"
docRef = await addDoc(this.productosCollectionRef, new Producto(34,"Pastel de Zanahoria",76,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(35,"Palomitas con mantequilla",51,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(36,"Frambuesa",1080,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(37,"Pastel de nata",153,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(38,"Cereza",1620,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(39,"Pastel de bayas",51,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(40,"Lingote de plata",480,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(41,"Pastel de Queso",204,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(42,"Palomitas con chile",102,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(43,"Chile",240,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(44,"Lingote de platino",960,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(45,"Zumo de Zanahoria",25,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(46,"Magdalena de mora",38,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(47,"Magdalena de frambuesa",38,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(48,"Lingote de oro",720,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(49,"Hamburguesa de pescado",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(50,"Pescado",120,9,,"S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(51,"Zumo de manzana",102,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(52,"Gratinado de pescado",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(53,"Tarta de manzana",127,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(54,"Mora",2040,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(55,"Zumo de cereza",127,2,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(56,"Tomate",360,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(57,"Helado de vainilla",102,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(58,"Zumo de tomate",76,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(59,"Leche de cabra",480,9,,"S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(60,"Queso de cabra",76,7,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(61,"Polo de Cereza",153,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(62,"Pizza",12,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(63,"Tomates asados",76,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(64,"Fresa",480,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(65,"Helado de fresa",204,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(66,"Tarta de feta",76,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(67,"Mermelada de manzana",306,1,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(68,"Patata",220,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(69,"Patata asada",29,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(70,"Pastel de chocolate",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(71,"Gratinado de bacon",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(72,"Carbón refinado",360,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(73,"Cacao",1800,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(74,"Lingote de hierro",420,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(75,"Pastel de fresas",153,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(76,"Zumo de bayas",153,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(77,"Mermelada de Frambuesa",357,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(78,"Pizza picante",15,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(79,"Mermelada de cereza",357,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(80,"Pastelitos de patata",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(81,"Gratinado de carne",85,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(82,"Pan de patata",38,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(83,"Mermelada de mora",348,2,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(84,"Helado de chocolate",127,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(85,"Pulsera",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(86,"Collar",153,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(87,"Pescado y patatas",76,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(88,"café Expreso",5,,,,,"Cafetería"
docRef = await addDoc(this.productosCollectionRef, new Producto(89,"Tela de algodón",25,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(90,"Chaparreras de lana",76,,,,,"Coser"
docRef = await addDoc(this.productosCollectionRef, new Producto(92,"Camisa de algodón",38,,,,,"Coser"
docRef = await addDoc(this.productosCollectionRef, new Producto(93,"Granos de café",2500,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(94,"café con leche",10,,,,,"Cafetería"
docRef = await addDoc(this.productosCollectionRef, new Producto(95,"Pulsera metálica",76,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(96,"Vestido violeta",114,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(97,"Palomitas con chocolate",127,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(98,"café Moca",15,0,,,,"Cafetería"
docRef = await addDoc(this.productosCollectionRef, new Producto(99,"Langosta",500,11,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(100,"Moca con frambuesa",30,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(101,"Pizza de Marisco",12,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(102,"Sopa de langosta",127,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(103,"Sopa de tomate",76,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(104,"Chocolate caliente",25,0,,,,"Cafetería"
docRef = await addDoc(this.productosCollectionRef, new Producto(105,"Miel",17,8,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(106,"Tarta de manzana y miel",200,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(108,"Brocheta de langosta",34,,,,,"Barbacoa"
docRef = await addDoc(this.productosCollectionRef, new Producto(109,"Panal",30,9,,"S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(110,"Pastel de manzana y miel",170,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(112,"Bufanda roja",127,,,,,"Telar"
docRef = await addDoc(this.productosCollectionRef, new Producto(113,"Sopa de calabaza",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(114,"Palomitas con miel",76,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(115,"algodón",150,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(116,"Mermelada de fresa",382,1,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(119,"Cera de abejas",45,1,,,,"Miel"
docRef = await addDoc(this.productosCollectionRef, new Producto(121,"Vela de fresa",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(123,"Vela de frambuesa",89,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(124,"Manzana caramelizada",102,3,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(125,"Caramelos",76,,,,,"Caramelos"
docRef = await addDoc(this.productosCollectionRef, new Producto(127,"Sopa de pescado",153,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(128,"Almohada",155,,,,,"Coser"
docRef = await addDoc(this.productosCollectionRef, new Producto(129,"Pluma de pato",180,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(131,"Salsa de soja",153,1,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(132,"Makis",60,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(133,"Arroz",45,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(134,"Aceitunas",1500,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(135,"Piruleta",612,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(136,"Lechuga",200,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(137,"Ensalada griega",76,,,,,"Ensaladas"
docRef = await addDoc(this.productosCollectionRef, new Producto(138,"Manta",178,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(139,"Sushi de langosta",60,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(140,"Aceite de oliva",38,0,,,,"Salsas"
docRef = await addDoc(this.productosCollectionRef, new Producto(141,"Gominolas",1224,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(142,"S.vegetal",34,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(143,"Ensalada con bacon",89,0,,,,"Ensaladas"
docRef = await addDoc(this.productosCollectionRef, new Producto(144,"Mayonesa",12,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(146,"Sushi de huevo",120,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(147,"Cóctel de marisco",102,0,,,,"Ensaladas"
docRef = await addDoc(this.productosCollectionRef, new Producto(148,"S.de Bacon",85,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(149,"Smoothie de bayas",63,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(150,"S.de huevo",68,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(151,"Smoothie verde",38,16,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(152,"Limón",1440,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(154,"Cuajada de limón",21,,,,,"Salsas"
docRef = await addDoc(this.productosCollectionRef, new Producto(156,"Pasta fresca",15,1,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(157,"Ensalada de pasta",127,,,,,"Ensaladas"
docRef = await addDoc(this.productosCollectionRef, new Producto(158,"Tarta de limón",114,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(159,"Salsa de tomate",25,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(160,"Tostada con miel",51,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(161,"Pastel de limón",127,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(162,"Smoothie de Yogur",51,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(164,"Sombrero de Cloch�",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(165,"Vela de limón",114,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(166,"Sombrero de copa",178,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(167,"�oquis",80,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(168,"Fideo de arroz",20,1,,,,"Pasta M�quina"
docRef = await addDoc(this.productosCollectionRef, new Producto(169,"Sopa de fideos",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(170,"Sombrero de playa",127,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(171,"Mermelada de Naranja",433,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(172,"Naranja",1920,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(173,"Zumo de naranja",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(174,"Perrito caliente",30,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(175,"Cebolla a la parrilla",51,,,,,"Barbacoa"
docRef = await addDoc(this.productosCollectionRef, new Producto(176,"Cebolla",300,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(177,"Sopa de cebolla",127,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(178,"Lasa�a",100,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(179,"Tarta de melocot�n",127,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(180,"Melocot�n",1920,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(182,"Perrito de maíz",60,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(183,"Sorbete de naranja",178,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(184,"Salsa picante",17,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(185,"Sopa de patata",127,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(186,"Taco",45,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(187,"Taco de pescado",90,3,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(188,"Sopa de langosta",120,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(189,"Mermelada de melocot�n",408,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(190,"Pasta con langosta",120,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(191,"Perrito con cebolla",75,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(192,"T� verde",30,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(194,"Hojas de t�",390,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(195,"T� con leche",45,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(196,"Ensalada de frutas",102,,,,,"Ensaladas"
docRef = await addDoc(this.productosCollectionRef, new Producto(197,"Quesudilla",60,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(198,"T� con miel",40,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(199,"Helado de melocot�n",153,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(200,"Olivada",38,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(201,"Ramo r�stico",45,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(202,"Rollito de verano",51,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(203,"Perrito vegetariano",45,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(204,"Chal de flores",76,,,,,"Telar"
docRef = await addDoc(this.productosCollectionRef, new Producto(205,"Girasoles",90,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(206,"Pasta carbonara",150,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(207,"Uva",150,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(208,"Zumo de uva",127,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(209,"Helado de melocot�n",153,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(210,"Ensalada veraniega",153,,,,,"Ensaladas"
docRef = await addDoc(this.productosCollectionRef, new Producto(211,"Mermelada de uva",331,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(212,"Corona de flores",102,,,,,"Sombrerer�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(213,"Peon�as",240,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(214,"T� con limón",20,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(216,"Nachos",75,6,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(217,"Batido mixto",25,,,,,"Licuadora"
docRef = await addDoc(this.productosCollectionRef, new Producto(218,"Helado de menta",114,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(219,"Menta",180,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(220,"Maki grande",90,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(221,"Crudit�s",102,,,,,"Ensaladas"
docRef = await addDoc(this.productosCollectionRef, new Producto(222,"Pimiento",270,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(223,"S.de cebolla y queso",76,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(224,"Latte Caramelo",15,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(225,"café helado de pl�tano",20,0,,,,"Cafetería"
docRef = await addDoc(this.productosCollectionRef, new Producto(226,"Pl�tano",1620,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(227,"Pasta picante",90,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(228,"Pastel de frutas",153,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(229,"T� con naranja",40,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(230,"Sopa de pimiento",51,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(231,"Bizcocho de pi�a",63,0,,,,"Pasteler�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(232,"Pi�a",30,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(233,"Zumo de pi�a",38,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(234,"S.de pepino",35,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(235,"Pepino",35,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(236,"Ramo de caramelos",20,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(237,"Pan de pl�tano",25,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(238,"Berenjena asada",34,,,,,"Barbacoa"
docRef = await addDoc(this.productosCollectionRef, new Producto(239,"Berenjena",40,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(240,"Batido de pepino",34,,,,,"Licuadora"
docRef = await addDoc(this.productosCollectionRef, new Producto(241,"Sopa de brocol�",63,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(242,"Pasta con brocol�",60,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(243,"Brocol�",80,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(245,"Zumo de sand�a",51,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(246,"Sand�a",300,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(247,"T� helado",30,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(248,"Tostada de queso de cabra",42,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(249,"Ramo delicado",30,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(250,"Tortitas de pl�tano",51,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(251,"Vela floral",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(252,"Mermelada de ciruela",255,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(253,"Ciruela",1920,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(254,"Banana split",178,,,,,"Helader�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(255,"T� de menta",35,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(257,"Crocante de s�samo",51,,,,,"Caramelos"
docRef = await addDoc(this.productosCollectionRef, new Producto(259,"Pastel de berenjena",38,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(260,"Fondue de Chocolate",25,,,,,"Fondue"
docRef = await addDoc(this.productosCollectionRef, new Producto(261,"Chocolate",1020,8,,,,"Caramelos"
docRef = await addDoc(this.productosCollectionRef, new Producto(262,"T� de manzana y jengibre",30,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(263,"Jengibre",150,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(265,"Fondue de bacon",30,,,,,"Fondue"
docRef = await addDoc(this.productosCollectionRef, new Producto(266,"Pan de ajo",12,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(267,"Ensalada de remolacha",38,,,,,"Ensaladas"
docRef = await addDoc(this.productosCollectionRef, new Producto(268,"Remolacha",40,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(269,"Chiles fritos",40,,,,,"Freidur�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(270,"Salteado de tofu",75,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(271,"S�samo",60,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(272,"Ensalada con setas",51,,,,,"Ensaladas"
docRef = await addDoc(this.productosCollectionRef, new Producto(273,"Setas",20,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(274,"Brocheta de pescado",25,,,,,"Barbacoa"
docRef = await addDoc(this.productosCollectionRef, new Producto(275,"Fondue de Queso",20,,,,,"Fondue"
docRef = await addDoc(this.productosCollectionRef, new Producto(276,"Batido de cacao",34,0,,,,"Licuadora"
docRef = await addDoc(this.productosCollectionRef, new Producto(277,"Empanadas de manzana",20,,,,,"Freidur�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(278,"Patatas con bacon",25,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(279,"S. Cacahuete y Mermelada",21,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(280,"Verduras asadas",21,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(281,"Pasta con setas",75,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(283,"Pescado picante",90,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(284,"Arroz frito",60,0,,,,"Wok"
docRef = await addDoc(this.productosCollectionRef, new Producto(285,"D�nut Cl�sico",15,0,,,,"Donuter�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(286,"D�nut crocanti",30,,,,,"Donuter�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(287,"D�nut con crema",25,,,,,"Donuter�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(288,"D�nut con bacon",30,,,,,"Donuter�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(289,"D�nut con virutas",20,0,,,,"Donuter�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(290,"Mascarilla de miel",90,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(292,"Jab�n exfoliante",60,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(293,"Loci�n de limón",75,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(294,"Jab�n de miel",60,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(295,"Batido de ciruela",29,,,,,"Licuadora"
docRef = await addDoc(this.productosCollectionRef, new Producto(296,"Pastel de setas",51,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(297,"Col",45,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(298,"Ramo de aniversario",20,5,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(299,"Sopa de col",76,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(300,"Lirios",90,9,"Silo","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(301,"Galleta de jengibre",25,,,,,"Panadería"
docRef = await addDoc(this.productosCollectionRef, new Producto(302,"D�nut relleno",35,,,,,"Donuter�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(303,"Rollo de chocolate",76,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(304,"Cacahuetes garrapi�ados",34,,,,,"Caramelos"
docRef = await addDoc(this.productosCollectionRef, new Producto(305,"Kinchi",255,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(306,"Velas coloridas",93,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(307,"Aperitvo salado",38,,,,,"Palomitera"
docRef = await addDoc(this.productosCollectionRef, new Producto(308,"Pescado en lata",187,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(309,"Batido de cacahuete",85,,,,,"Helader�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(310,"Cacahuetes",420,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(312,"Fruta deshidratada",153,,,,,"Conservas"
docRef = await addDoc(this.productosCollectionRef, new Producto(313,"Zumo de maracuy�",38,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(314,"Ensalada de col",63,,,,,"Ensaladas"
docRef = await addDoc(this.productosCollectionRef, new Producto(315,"Mermelada de maracuy�",272,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(316,"Tarta de chocolate",63,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(317,"Chocolatinas fritas",15,,,,,"Freidur�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(318,"Pimientos rellenos",17,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(319,"Vinagreta de maracuy�",25,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(320,"Ramo de verduras",15,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(321,"Pepinillos",204,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(322,"Batido de s�samo negro",38,,,,,"Licuadora"
docRef = await addDoc(this.productosCollectionRef, new Producto(323,"algodón de Azúcar",25,,,,,"Caramelos"
docRef = await addDoc(this.productosCollectionRef, new Producto(324,"Fideos con salsa de cacahuete",45,,,,,"Wok"
docRef = await addDoc(this.productosCollectionRef, new Producto(325,"Sopa de setas",68,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(326,"Tarta de maracuy�",42,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(327,"Helado de s�samo",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(328,"Helado de coco",12,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(329,"Zumo de mango",42,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(330,"Batido tropical",34,,,,,"Licuadora"
docRef = await addDoc(this.productosCollectionRef, new Producto(331,"Wrap de humus",25,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(332,"Humus",25,2,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(333,"Zumo de guayaba",46,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(334,"Pastel de granada",108,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(335,"Fudge de menta",150,,,,,"Fudge"
docRef = await addDoc(this.productosCollectionRef, new Producto(336,"Fudge de chocolate",120,,,,,"Fudge"
docRef = await addDoc(this.productosCollectionRef, new Producto(337,"Bolas de arroz",45,,,,,"Sushi"
docRef = await addDoc(this.productosCollectionRef, new Producto(338,"Yogur tropical",60,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(339,"Yogur",120,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(340,"Affogato",17,,,,,"Helader�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(341,"Estofado de chile",120,,,,,"Estofados"
docRef = await addDoc(this.productosCollectionRef, new Producto(342,"Falafel",55,,,,,"Freidur�a"
docRef = await addDoc(this.productosCollectionRef, new Producto(343,"Fondue tropical",35,,,,,"Fondue"
docRef = await addDoc(this.productosCollectionRef, new Producto(344,"Tetera",240,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(345,"Compota de Guayaba",221,,,,,"Conservas"
docRef = await addDoc(this.productosCollectionRef, new Producto(346,"Fudge de chile",170,,,,,"Fudge"
docRef = await addDoc(this.productosCollectionRef, new Producto(347,"Bolitas de coco",25,,,,,"Panadería"
docRef = await addDoc(this.productosCollectionRef, new Producto(348,"Sorbete de frutas",51,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(349,"Samosa",75,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(350,"Maceta con flor",220,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(351,"Taza de arcilla",200,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(352,"Fudge de cacahuete",90,,,,,"Fudge"
docRef = await addDoc(this.productosCollectionRef, new Producto(353,"Quich� de esp�rragos",102,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(354,"Esp�rragos a a la parrilla",63,,,,,"Barbacoa"
docRef = await addDoc(this.productosCollectionRef, new Producto(355,"T� de granada",35,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(356,"Tortilla de queso",90,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(358,"Haz de trigo",26,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(359,"Comida de cerdos",17,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(360,"Yogur de fresa",40,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(361,"Tortilla colorida",60,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(362,"Sopa de esp�rragos",60,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(363,"Fudge de limón",110,,,,,"Fudge"
docRef = await addDoc(this.productosCollectionRef, new Producto(364,"Tortilla de primavera",40,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(365,"Estofado de invierno",140,,,,,"Estofados"
docRef = await addDoc(this.productosCollectionRef, new Producto(368,"Colgante floral",51,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(369,"Estofado de garbanzos",90,1,,,,"Estofados"
docRef = await addDoc(this.productosCollectionRef, new Producto(370,"Tortilla de arroz",120,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(371,"Cupcake",40,0,,,,"Cupcakes"
docRef = await addDoc(this.productosCollectionRef, new Producto(372,"C.de guayaba",70,,,,,"Cupcakes"
docRef = await addDoc(this.productosCollectionRef, new Producto(373,"C.Tropical",90,,,,,"Cupcakes"
docRef = await addDoc(this.productosCollectionRef, new Producto(374,"C.de galleta",120,,,,,"Cupcakes"
docRef = await addDoc(this.productosCollectionRef, new Producto(375,"Tortilla de patata",75,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(376,"Gofres normales",25,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(377,"G.con frutos rojos",35,0,,,,"Gofrera"
docRef = await addDoc(this.productosCollectionRef, new Producto(378,"Ramo colorido",20,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(379,"Gofres con chocolate",40,,,,,"Gofrera"
docRef = await addDoc(this.productosCollectionRef, new Producto(380,"Gofres frutos rojos",35,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(381,"Ensalada de naranja",38,,,,,"Ensaladas"

docRef = await addDoc(this.productosCollectionRef, new Producto(385,"Cabra de chocolate",90,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(386,"G.de huevos con bacon",45,,,,,"Gofrera"
docRef = await addDoc(this.productosCollectionRef, new Producto(387,"Aceite esencial de limón",10,,,,,"Aceites esenciales"
docRef = await addDoc(this.productosCollectionRef, new Producto(388,"Aceite esencial de menta",15,,,,,"Aceites esenciales"
docRef = await addDoc(this.productosCollectionRef, new Producto(389,"Bol de desayuno",50,,,,,"Gachas"
docRef = await addDoc(this.productosCollectionRef, new Producto(390,"Avena",6,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(391,"Esp�rragos",360,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(392,"Coco",1440,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(393,"Guayaba",1440,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(394,"Garbanzos",60,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(395,"Mango",1920,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(396,"Maracuy�",60,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(397,"Granada",1620,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(398,"Ajos",30,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(399,"Arcilla",110,9,"SILO","S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(400,"Barritas de pi�a y coco",34,0,,,,"Panadería"
docRef = await addDoc(this.productosCollectionRef, new Producto(401,"Gachas con manzana",20,,,,,"Gachas"
docRef = await addDoc(this.productosCollectionRef, new Producto(402,"Gachas dulces",45,,,,,"Gachas"
docRef = await addDoc(this.productosCollectionRef, new Producto(403,"Gachas reci�n hechas",35,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(404,"Aceite esencial de jengibre",20,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(405,"Jab�n lujoso",70,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(406,"Batido de vainilla",45,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(407,"Batido de moca",30,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(409,"Batido de frutas",35,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(415,"Aceite esencial de manzanilla",10,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(416,"T� de manzanilla",20,0,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(417,"Manzanilla",20,9,,"S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(418,"Difusor fresco",20,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(419,"Almohada relajante",51,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(420,"Difusor relajante",25,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(421,"Perfume c�trico",15,,,,,
docRef = await addDoc(this.productosCollectionRef, new Producto(422,"Ar�ndanos",840,9,,"S",9,
docRef = await addDoc(this.productosCollectionRef, new Producto(423,"G.de Ar�ndanos",42,,,,,
