import { PokemonTipoPokemonModel } from './zzzpokemon-tipo-pokemon.model';

export class PokemonTipoPokemonIniciales {

misPokemonTipoPokemonIniciales: PokemonTipoPokemonModel[] = [
    new PokemonTipoPokemonModel("Abomasnow", "Hielo"),
new PokemonTipoPokemonModel("Abomasnow", "Planta"),
new PokemonTipoPokemonModel("Absol", "Siniestro"),
new PokemonTipoPokemonModel("Accelgor", "Bicho"),
new PokemonTipoPokemonModel("Aerodactyl", "Roca"),
new PokemonTipoPokemonModel("Aerodactyl", "Volador"),
new PokemonTipoPokemonModel("Aggron", "Acero"),
new PokemonTipoPokemonModel("Aggron", "Roca"),
new PokemonTipoPokemonModel("Alakazam", "Psíquico"),
new PokemonTipoPokemonModel("Ambipom", "Normal"),
new PokemonTipoPokemonModel("Amoonguss", "Planta"),
new PokemonTipoPokemonModel("Amoonguss", "Veneno"),
new PokemonTipoPokemonModel("Ampharos", "Eléctrico"),
new PokemonTipoPokemonModel("Annihilape", "Fantasma"),
new PokemonTipoPokemonModel("Annihilape", "Lucha"),
new PokemonTipoPokemonModel("Arboliva", "Normal"),
new PokemonTipoPokemonModel("Arboliva", "Planta"),
new PokemonTipoPokemonModel("Arcanine", "Fuego"),
new PokemonTipoPokemonModel("Arcanine Hisuian", "Fuego"),
new PokemonTipoPokemonModel("Arcanine Hisuian", "Roca"),
new PokemonTipoPokemonModel("Archeops", "Roca"),
new PokemonTipoPokemonModel("Archeops", "Volador"),
new PokemonTipoPokemonModel("Armaldo", "Bicho"),
new PokemonTipoPokemonModel("Armaldo", "Roca"),
new PokemonTipoPokemonModel("Aromatisse", "Hada"),
new PokemonTipoPokemonModel("Articuno", "Hielo"),
new PokemonTipoPokemonModel("Articuno", "Volador"),
new PokemonTipoPokemonModel("Aurorus", "Hielo"),
new PokemonTipoPokemonModel("Aurorus", "Roca"),
new PokemonTipoPokemonModel("Avalugg", "Hielo"),
new PokemonTipoPokemonModel("Banette", "Fantasma"),
new PokemonTipoPokemonModel("Barbaracle", "Agua"),
new PokemonTipoPokemonModel("Barbaracle", "Roca"),
new PokemonTipoPokemonModel("Baxcalibur", "Dragón"),
new PokemonTipoPokemonModel("Baxcalibur", "Hielo"),
new PokemonTipoPokemonModel("Beartic", "Hielo"),
new PokemonTipoPokemonModel("Beheeyem", "Psíquico"),
new PokemonTipoPokemonModel("Bellibol", "Eléctrico"),
new PokemonTipoPokemonModel("Bewear", "Lucha"),
new PokemonTipoPokemonModel("Bewear", "Normal"),
new PokemonTipoPokemonModel("Blastoise", "Agua"),
new PokemonTipoPokemonModel("Blaziken", "Fuego"),
new PokemonTipoPokemonModel("Blaziken", "Lucha"),
new PokemonTipoPokemonModel("Blissey", "Normal"),
new PokemonTipoPokemonModel("Braviary", "Normal"),
new PokemonTipoPokemonModel("Braviary", "Volador"),
new PokemonTipoPokemonModel("Breloom", "Lucha"),
new PokemonTipoPokemonModel("Breloom", "Planta"),
new PokemonTipoPokemonModel("Buzzwole", "Bicho"),
new PokemonTipoPokemonModel("Buzzwole", "Lucha"),
new PokemonTipoPokemonModel("Cacturne", "Planta"),
new PokemonTipoPokemonModel("Cacturne", "Siniestro"),
new PokemonTipoPokemonModel("Camerupt", "Fuego"),
new PokemonTipoPokemonModel("Camerupt", "Tierra"),
new PokemonTipoPokemonModel("Cetitan", "Hielo"),
new PokemonTipoPokemonModel("Chandelure", "Fantasma"),
new PokemonTipoPokemonModel("Chandelure", "Fuego"),
new PokemonTipoPokemonModel("Charizard", "Fuego"),
new PokemonTipoPokemonModel("Charizard", "Volador"),
new PokemonTipoPokemonModel("Chesnaught", "Lucha"),
new PokemonTipoPokemonModel("Chesnaught", "Planta"),
new PokemonTipoPokemonModel("Cinccino", "Normal"),
new PokemonTipoPokemonModel("Cinderace", "Fuego"),
new PokemonTipoPokemonModel("Clawitzer", "Agua"),
new PokemonTipoPokemonModel("Clefable", "Hada"),
new PokemonTipoPokemonModel("Cloyster", "Agua"),
new PokemonTipoPokemonModel("Cloyster", "Hielo"),
new PokemonTipoPokemonModel("Conkeldurr", "Lucha"),
new PokemonTipoPokemonModel("Crabominable", "Hielo"),
new PokemonTipoPokemonModel("Crabominable", "Lucha"),
new PokemonTipoPokemonModel("Cradily", "Planta"),
new PokemonTipoPokemonModel("Cradily", "Roca"),
new PokemonTipoPokemonModel("Crawdaunt", "Agua"),
new PokemonTipoPokemonModel("Crawdaunt", "Siniestro"),
new PokemonTipoPokemonModel("Cresselia", "Psíquico"),
new PokemonTipoPokemonModel("Crobat", "Veneno"),
new PokemonTipoPokemonModel("Crobat", "Volador"),
new PokemonTipoPokemonModel("Crustle", "Bicho"),
new PokemonTipoPokemonModel("Crustle", "Roca"),
new PokemonTipoPokemonModel("Cryogonal", "Hielo"),
new PokemonTipoPokemonModel("Darkrai", "Siniestro"),
new PokemonTipoPokemonModel("Darmanitan - Standard", "Fuego"),
new PokemonTipoPokemonModel("Darmanitan de Galar", "Hielo"),
new PokemonTipoPokemonModel("Decidueye", "Fantasma"),
new PokemonTipoPokemonModel("Decidueye", "Planta"),
new PokemonTipoPokemonModel("Decidueye - Hisui", "Lucha"),
new PokemonTipoPokemonModel("Decidueye - Hisui", "Planta"),
new PokemonTipoPokemonModel("Delphox", "Fuego"),
new PokemonTipoPokemonModel("Delphox", "Psíquico"),
new PokemonTipoPokemonModel("Dialga", "Acero"),
new PokemonTipoPokemonModel("Dialga", "Dragón"),
new PokemonTipoPokemonModel("Dialga Hisui", "Acero"),
new PokemonTipoPokemonModel("Dialga Hisui", "Dragón"),
new PokemonTipoPokemonModel("Dodrio", "Normal"),
new PokemonTipoPokemonModel("Dodrio", "Volador"),
new PokemonTipoPokemonModel("Donphan", "Tierra"),
new PokemonTipoPokemonModel("Dragalge", "Dragón"),
new PokemonTipoPokemonModel("Dragalge", "Veneno"),
new PokemonTipoPokemonModel("Dragapult", "Dragón"),
new PokemonTipoPokemonModel("Dragapult", "Fantasma"),
new PokemonTipoPokemonModel("Dragonite", "Dragón"),
new PokemonTipoPokemonModel("Dragonite", "Volador"),
new PokemonTipoPokemonModel("Drapion", "Siniestro"),
new PokemonTipoPokemonModel("Drapion", "Veneno"),
new PokemonTipoPokemonModel("Drifblim", "Fantasma"),
new PokemonTipoPokemonModel("Drifblim", "Volador"),
new PokemonTipoPokemonModel("Dudunsparce (Forma Binodular)", "Normal"),
new PokemonTipoPokemonModel("Durant", "Acero"),
new PokemonTipoPokemonModel("Durant", "Bicho"),
new PokemonTipoPokemonModel("Dusknoir", "Fantasma"),
new PokemonTipoPokemonModel("Eelektross", "Eléctrico"),
new PokemonTipoPokemonModel("Electivire", "Eléctrico"),
new PokemonTipoPokemonModel("Electrode Hisuain", "Eléctrico"),
new PokemonTipoPokemonModel("Electrode Hisuain", "Planta"),
new PokemonTipoPokemonModel("Emboar", "Fuego"),
new PokemonTipoPokemonModel("Emboar", "Lucha"),
new PokemonTipoPokemonModel("Empoleon", "Acero"),
new PokemonTipoPokemonModel("Empoleon", "Agua"),
new PokemonTipoPokemonModel("Enamorus Avatar", "Hada"),
new PokemonTipoPokemonModel("Enamorus Avatar", "Volador"),
new PokemonTipoPokemonModel("Entei", "Fuego"),
new PokemonTipoPokemonModel("Escavalier", "Acero"),
new PokemonTipoPokemonModel("Escavalier", "Bicho"),
new PokemonTipoPokemonModel("Espeon", "Psíquico"),
new PokemonTipoPokemonModel("Excadrill", "Acero"),
new PokemonTipoPokemonModel("Excadrill", "Tierra"),
new PokemonTipoPokemonModel("Exeggutor Alola", "Dragón"),
new PokemonTipoPokemonModel("Exeggutor Alola", "Planta"),
new PokemonTipoPokemonModel("Exeggutor Normal", "Planta"),
new PokemonTipoPokemonModel("Exeggutor Normal", "Psíquico"),
new PokemonTipoPokemonModel("Exploud", "Normal"),
new PokemonTipoPokemonModel("Feraligatr", "Agua"),
new PokemonTipoPokemonModel("Flareon", "Fuego"),
new PokemonTipoPokemonModel("Floatzel", "Agua"),
new PokemonTipoPokemonModel("Florges - Blue", "Hada"),
new PokemonTipoPokemonModel("Florges - Orange", "Hada"),
new PokemonTipoPokemonModel("Florges - Red", "hada"),
new PokemonTipoPokemonModel("Florges - White", "Hada"),
new PokemonTipoPokemonModel("Florges . Yellow", "Hada"),
new PokemonTipoPokemonModel("Flygon", "Dragón"),
new PokemonTipoPokemonModel("Flygon", "Tierra"),
new PokemonTipoPokemonModel("Forretress", "Acero"),
new PokemonTipoPokemonModel("Forretress", "Bicho"),
new PokemonTipoPokemonModel("Gallade", "Lucha"),
new PokemonTipoPokemonModel("Gallade", "Psíquico"),
new PokemonTipoPokemonModel("Garbodor", "Veneno"),
new PokemonTipoPokemonModel("Garchomp", "Dragón"),
new PokemonTipoPokemonModel("Garchomp", "Tierra"),
new PokemonTipoPokemonModel("Gardevoir", "Hada"),
new PokemonTipoPokemonModel("Gardevoir", "Psíquico"),
new PokemonTipoPokemonModel("Gastrodom", "Agua"),
new PokemonTipoPokemonModel("Gastrodom", "Tierra"),
new PokemonTipoPokemonModel("Genesect", "Acero"),
new PokemonTipoPokemonModel("Genesect", "Bicho"),
new PokemonTipoPokemonModel("Gengar", "Fantasma"),
new PokemonTipoPokemonModel("Gengar", "Veneno"),
new PokemonTipoPokemonModel("Gigalith", "Roca"),
new PokemonTipoPokemonModel("Giratina Altered", "Dragón"),
new PokemonTipoPokemonModel("Giratina Altered", "Fantasma"),
new PokemonTipoPokemonModel("Giratina Origen", "Dragón"),
new PokemonTipoPokemonModel("Giratina Origen", "Fantasma"),
new PokemonTipoPokemonModel("Glaceon", "Hielo"),
new PokemonTipoPokemonModel("Gliscor", "Tierra"),
new PokemonTipoPokemonModel("Gliscor", "Volador"),
new PokemonTipoPokemonModel("Golduck", "Agua"),
new PokemonTipoPokemonModel("Golem Alola", "Eléctrico"),
new PokemonTipoPokemonModel("Golem Alola", "Roca"),
new PokemonTipoPokemonModel("Golem Normal", "Roca"),
new PokemonTipoPokemonModel("Golem Normal", "Tierra"),
new PokemonTipoPokemonModel("Golisopod", "Agua"),
new PokemonTipoPokemonModel("Golisopod", "Bicho"),
new PokemonTipoPokemonModel("Golurk", "Fantasma"),
new PokemonTipoPokemonModel("Golurk", "Tierra"),
new PokemonTipoPokemonModel("Goodra", "Dragón"),
new PokemonTipoPokemonModel("Gothielle", "Psíquico"),
new PokemonTipoPokemonModel("Gourgeist", "Fantasma"),
new PokemonTipoPokemonModel("Gourgeist", "Planta"),
new PokemonTipoPokemonModel("Granbull", "Hada"),
new PokemonTipoPokemonModel("Greninja", "Agua"),
new PokemonTipoPokemonModel("Greninja", "Siniestro"),
new PokemonTipoPokemonModel("Groudon", "Tierra"),
new PokemonTipoPokemonModel("Grumpig", "Psíquico"),
new PokemonTipoPokemonModel("Gumshoos", "Normal"),
new PokemonTipoPokemonModel("Gyarados", "Acero"),
new PokemonTipoPokemonModel("Gyarados", "Veneno"),
new PokemonTipoPokemonModel("Hariyama", "Lucha"),
new PokemonTipoPokemonModel("Hatterene", "Hada"),
new PokemonTipoPokemonModel("Hatterene", "Psíquico"),
new PokemonTipoPokemonModel("Haxorus", "Dragón"),
new PokemonTipoPokemonModel("Heatmor", "Fuego"),
new PokemonTipoPokemonModel("Heatran", "Acero"),
new PokemonTipoPokemonModel("Heatran", "Fuego"),
new PokemonTipoPokemonModel("Heliolisk", "Eléctrico"),
new PokemonTipoPokemonModel("Heliolisk", "Normal"),
new PokemonTipoPokemonModel("Heracross", "Bicho"),
new PokemonTipoPokemonModel("Heracross", "Lucha"),
new PokemonTipoPokemonModel("Hippodown", "Tierra"),
new PokemonTipoPokemonModel("Hitmonchan", "Lucha"),
new PokemonTipoPokemonModel("Hitmonlee", "Lucha"),
new PokemonTipoPokemonModel("Honchkrow", "Siniestro"),
new PokemonTipoPokemonModel("Honchkrow", "Volador"),
new PokemonTipoPokemonModel("Ho-oh", "Fuego"),
new PokemonTipoPokemonModel("Ho-oh", "Volador"),
new PokemonTipoPokemonModel("Houndoom", "Fuego"),
new PokemonTipoPokemonModel("Houndoom", "Siniestro"),
new PokemonTipoPokemonModel("Hydreigon", "Siniestro"),
new PokemonTipoPokemonModel("Hydreigon", "Volador"),
new PokemonTipoPokemonModel("Incineroar", "Fuego"),
new PokemonTipoPokemonModel("Incineroar", "Siniestro"),
new PokemonTipoPokemonModel("Infernape", "Fuego"),
new PokemonTipoPokemonModel("Infernape", "Lucha"),
new PokemonTipoPokemonModel("Inteleon", "Agua"),
new PokemonTipoPokemonModel("Jolteon", "Eléctrico"),
new PokemonTipoPokemonModel("Jynx", "Hielo"),
new PokemonTipoPokemonModel("Jynx", "Psíquico"),
new PokemonTipoPokemonModel("Kabutops", "Agua"),
new PokemonTipoPokemonModel("Kabutops", "Roca"),
new PokemonTipoPokemonModel("Kangaskhan", "Normal"),
new PokemonTipoPokemonModel("Kingdra", "Agua"),
new PokemonTipoPokemonModel("Kingdra", "Dragón"),
new PokemonTipoPokemonModel("Kingler", "Agua"),
new PokemonTipoPokemonModel("Komala", "Normal"),
new PokemonTipoPokemonModel("Kommo-o", "Dragón"),
new PokemonTipoPokemonModel("Kommo-o", "Lucha"),
new PokemonTipoPokemonModel("Kyogre", "Agua"),
new PokemonTipoPokemonModel("Kyurem", "Dragón"),
new PokemonTipoPokemonModel("Kyurem", "Hielo"),
new PokemonTipoPokemonModel("Landorus", "Tierra"),
new PokemonTipoPokemonModel("Landorus", "Volador"),
new PokemonTipoPokemonModel("Landorus Therian", "Tierra"),
new PokemonTipoPokemonModel("Landorus Therian", "Volador"),
new PokemonTipoPokemonModel("Lapras", "Agua"),
new PokemonTipoPokemonModel("Lapras", "Hielo"),
new PokemonTipoPokemonModel("Latias", "Dragón"),
new PokemonTipoPokemonModel("Latias", "Psíquico"),
new PokemonTipoPokemonModel("Latios", "Dragón"),
new PokemonTipoPokemonModel("Latios", "Psíquico"),
new PokemonTipoPokemonModel("Leafeon", "Planta"),
new PokemonTipoPokemonModel("Lickilicky", "Normal"),
new PokemonTipoPokemonModel("Lilligant", "Planta"),
new PokemonTipoPokemonModel("Ludicolo", "Agua"),
new PokemonTipoPokemonModel("Ludicolo", "Planta"),
new PokemonTipoPokemonModel("Lugia", "Psíquico"),
new PokemonTipoPokemonModel("Lugia", "Volador"),
new PokemonTipoPokemonModel("Lunatone", "Psíquico"),
new PokemonTipoPokemonModel("Lunatone", "Roca"),
new PokemonTipoPokemonModel("Luxray", "Eléctrico"),
new PokemonTipoPokemonModel("Lycanroc Midday", "Roca"),
new PokemonTipoPokemonModel("Machamp", "Lucha"),
new PokemonTipoPokemonModel("Magmar", "Fuego"),
new PokemonTipoPokemonModel("Magmortar", "Fuego"),
new PokemonTipoPokemonModel("Magnezone", "Eléctrico"),
new PokemonTipoPokemonModel("Magnezone", "Volador"),
new PokemonTipoPokemonModel("Malamar", "Psíquico"),
new PokemonTipoPokemonModel("Malamar", "Siniestro"),
new PokemonTipoPokemonModel("Mamoswine", "Hielo"),
new PokemonTipoPokemonModel("Mamoswine", "Tierra"),
new PokemonTipoPokemonModel("Manectric", "Eléctrico"),
new PokemonTipoPokemonModel("Masquerain", "Bicho"),
new PokemonTipoPokemonModel("Masquerain", "Volador"),
new PokemonTipoPokemonModel("Meganium", "Planta"),
new PokemonTipoPokemonModel("Melmeltan", "Acero"),
new PokemonTipoPokemonModel("Meowscarada", "Planta"),
new PokemonTipoPokemonModel("Meowscarada", "Siniestro"),
new PokemonTipoPokemonModel("Metagross", "Acero"),
new PokemonTipoPokemonModel("Metagross", "Psíquico"),
new PokemonTipoPokemonModel("Mewtwo", "Psíquico"),
new PokemonTipoPokemonModel("Milotic", "Agua"),
new PokemonTipoPokemonModel("Miltank", "Normal"),
new PokemonTipoPokemonModel("Mismagius", "Fantasma"),
new PokemonTipoPokemonModel("Moltres", "Fuego"),
new PokemonTipoPokemonModel("Moltres", "Volador"),
new PokemonTipoPokemonModel("Mr.Mime", "Hada"),
new PokemonTipoPokemonModel("Mr.Mime", "Psíquico"),
new PokemonTipoPokemonModel("Muk Alola", "Siniestro"),
new PokemonTipoPokemonModel("Muk Alola", "Veneno"),
new PokemonTipoPokemonModel("Muk Normal", "Veneno"),
new PokemonTipoPokemonModel("Munna", "Psíquico"),
new PokemonTipoPokemonModel("Musharna", "Psíquico"),
new PokemonTipoPokemonModel("Nidoking", "Tierra"),
new PokemonTipoPokemonModel("Nidoking", "Veneno"),
new PokemonTipoPokemonModel("Nidoqueen", "Tierra"),
new PokemonTipoPokemonModel("Nidoqueen", "Veneno"),
new PokemonTipoPokemonModel("Nihilego", "Roca"),
new PokemonTipoPokemonModel("Nihilego", "Veneno"),
new PokemonTipoPokemonModel("Ninetales", "Hada"),
new PokemonTipoPokemonModel("Ninetales", "Hielo"),
new PokemonTipoPokemonModel("Noivern", "Dragón"),
new PokemonTipoPokemonModel("Noivern", "Volador"),
new PokemonTipoPokemonModel("Obstagoon", "Normal"),
new PokemonTipoPokemonModel("Obstagoon", "Siniestro"),
new PokemonTipoPokemonModel("Octillery", "Agua"),
new PokemonTipoPokemonModel("Oinkologne", "Normal"),
new PokemonTipoPokemonModel("Omastar", "Agua"),
new PokemonTipoPokemonModel("Omastar", "Roca"),
new PokemonTipoPokemonModel("Oranguru", "Normal"),
new PokemonTipoPokemonModel("Oranguru", "Psíquico"),
new PokemonTipoPokemonModel("Oricorio", "Fuego"),
new PokemonTipoPokemonModel("Oricorio", "Volador"),
new PokemonTipoPokemonModel("Overqwil", "Siniestro"),
new PokemonTipoPokemonModel("Overqwil", "Veneno"),
new PokemonTipoPokemonModel("Palkia", "Agua"),
new PokemonTipoPokemonModel("Palkia", "Dragón"),
new PokemonTipoPokemonModel("Palkia Hisui", "Agua"),
new PokemonTipoPokemonModel("Palkia Hisui", "Dragón"),
new PokemonTipoPokemonModel("Palosand", "Fantasma"),
new PokemonTipoPokemonModel("Palosand", "Tierra"),
new PokemonTipoPokemonModel("Passimian", "Lucha"),
new PokemonTipoPokemonModel("Pawmot", "Eléctrico"),
new PokemonTipoPokemonModel("Pawmot", "Lucha"),
new PokemonTipoPokemonModel("Pheromosa", "Bicho"),
new PokemonTipoPokemonModel("Pheromosa", "Lucha"),
new PokemonTipoPokemonModel("Piloswine", "Hielo"),
new PokemonTipoPokemonModel("Piloswine", "Tierra"),
new PokemonTipoPokemonModel("Pinsir", "Bicho"),
new PokemonTipoPokemonModel("Politoed", "Agua"),
new PokemonTipoPokemonModel("Poliwarth", "Agua"),
new PokemonTipoPokemonModel("Poliwarth", "Lucha"),
new PokemonTipoPokemonModel("Polteageist", "Fantasma"),
new PokemonTipoPokemonModel("Porygon-Z", "Normal"),
new PokemonTipoPokemonModel("Primarina", "Agua"),
new PokemonTipoPokemonModel("Primarina", "Hada"),
new PokemonTipoPokemonModel("Primeape", "Lucha"),
new PokemonTipoPokemonModel("Pyroar Hembra", "Acero"),
new PokemonTipoPokemonModel("Pyroar Hembra", "Fuego"),
new PokemonTipoPokemonModel("Pyroar macho", "Fuego"),
new PokemonTipoPokemonModel("Pyroar macho", "Normal"),
new PokemonTipoPokemonModel("Quaquaval", "Agua"),
new PokemonTipoPokemonModel("Quaquaval", "Lucha"),
new PokemonTipoPokemonModel("Raikou", "Eléctrico"),
new PokemonTipoPokemonModel("Rampardos", "Roca"),
new PokemonTipoPokemonModel("Rapidash", "Fuego"),
new PokemonTipoPokemonModel("Rapidash - Galarian", "Hada"),
new PokemonTipoPokemonModel("Rapidash - Galarian", "Psíquico"),
new PokemonTipoPokemonModel("Rayquaza", "Dragón"),
new PokemonTipoPokemonModel("Rayquaza", "Volador"),
new PokemonTipoPokemonModel("Regice", "Hielo"),
new PokemonTipoPokemonModel("Regigigas", "Normal"),
new PokemonTipoPokemonModel("Regirock", "Roca"),
new PokemonTipoPokemonModel("Reshiram", "Dragón"),
new PokemonTipoPokemonModel("Reshiram", "Fuego"),
new PokemonTipoPokemonModel("Reuniclus", "Psíquico"),
new PokemonTipoPokemonModel("Rhydon", "Roca"),
new PokemonTipoPokemonModel("Rhydon", "Tierra"),
new PokemonTipoPokemonModel("Rhyperior", "Roca"),
new PokemonTipoPokemonModel("Rhyperior", "Tierra"),
new PokemonTipoPokemonModel("Rillaboom", "Planta"),
new PokemonTipoPokemonModel("Roserade", "Planta"),
new PokemonTipoPokemonModel("Roserade", "Veneno"),
new PokemonTipoPokemonModel("Salamence", "Dragón"),
new PokemonTipoPokemonModel("Salamence", "Volador"),
new PokemonTipoPokemonModel("Samurott", "Agua"),
new PokemonTipoPokemonModel("Sandslash Alola", "Acero"),
new PokemonTipoPokemonModel("Sandslash Alola", "Hielo"),
new PokemonTipoPokemonModel("Sandslash normal", "Tierra"),
new PokemonTipoPokemonModel("Sawk", "Lucha"),
new PokemonTipoPokemonModel("Sawsbuck - Spring", "Normal"),
new PokemonTipoPokemonModel("Sawsbuck - Spring", "Planta"),
new PokemonTipoPokemonModel("Sawsbuck - Summer", "Normal"),
new PokemonTipoPokemonModel("Sawsbuck - Summer", "Planta"),
new PokemonTipoPokemonModel("Sawsbuck - Winter", "Normal"),
new PokemonTipoPokemonModel("Sawsbuck - Winter", "Planta"),
new PokemonTipoPokemonModel("Sawsbuck Autumm", "Normal"),
new PokemonTipoPokemonModel("Sawsbuck Autumm", "Planta"),
new PokemonTipoPokemonModel("Sceptile", "Planta"),
new PokemonTipoPokemonModel("Scizor", "Acero"),
new PokemonTipoPokemonModel("Scizor", "Bicho"),
new PokemonTipoPokemonModel("Scolipede", "Bicho"),
new PokemonTipoPokemonModel("Scolipede", "Veneno"),
new PokemonTipoPokemonModel("Scrafty", "Lucha"),
new PokemonTipoPokemonModel("Scrafty", "Siniestro"),
new PokemonTipoPokemonModel("Scyther", "Bicho"),
new PokemonTipoPokemonModel("Scyther", "Volador"),
new PokemonTipoPokemonModel("Seaking", "agua"),
new PokemonTipoPokemonModel("Seismitoad", "Agua"),
new PokemonTipoPokemonModel("Seismitoad", "Tierra"),
new PokemonTipoPokemonModel("Serperior", "Planta"),
new PokemonTipoPokemonModel("Shiftry", "Planta"),
new PokemonTipoPokemonModel("Shiftry", "Siniestro"),
new PokemonTipoPokemonModel("Sigilyph", "Psíquico"),
new PokemonTipoPokemonModel("Sigilyph", "Volador"),
new PokemonTipoPokemonModel("Simisear", "Fuego"),
new PokemonTipoPokemonModel("Sirfetch'd", "Lucha"),
new PokemonTipoPokemonModel("Skeledirge", "Fantasma"),
new PokemonTipoPokemonModel("Skeledirge", "Fuego"),
new PokemonTipoPokemonModel("Skutank", "Siniestro"),
new PokemonTipoPokemonModel("Skutank", "Veneno"),
new PokemonTipoPokemonModel("Slaking", "Normal"),
new PokemonTipoPokemonModel("Slowbro", "Agua"),
new PokemonTipoPokemonModel("Slowbro", "Psíquico"),
new PokemonTipoPokemonModel("Slowking", "Agua"),
new PokemonTipoPokemonModel("Slowking", "Psíquico"),
new PokemonTipoPokemonModel("Sneasler", "Lucha"),
new PokemonTipoPokemonModel("Sneasler", "Veneno"),
new PokemonTipoPokemonModel("Snorlax", "Normal"),
new PokemonTipoPokemonModel("Solrock", "Psíquico"),
new PokemonTipoPokemonModel("Solrock", "Roca"),
new PokemonTipoPokemonModel("Staraptor", "Normal"),
new PokemonTipoPokemonModel("Staraptor", "Volador"),
new PokemonTipoPokemonModel("Starmie", "Agua"),
new PokemonTipoPokemonModel("Starmie", "Psíquico"),
new PokemonTipoPokemonModel("Steelix", "Acero"),
new PokemonTipoPokemonModel("Steelix", "Tierra"),
new PokemonTipoPokemonModel("Stoutland", "Normal"),
new PokemonTipoPokemonModel("Suicune", "Agua"),
new PokemonTipoPokemonModel("Swampert", "Agua"),
new PokemonTipoPokemonModel("Swampert", "Tierra"),
new PokemonTipoPokemonModel("Talonflame", "Fuego"),
new PokemonTipoPokemonModel("Talonflame", "Volador"),
new PokemonTipoPokemonModel("Tangrowth", "Planta"),
new PokemonTipoPokemonModel("Tapu Bulu", "Hada"),
new PokemonTipoPokemonModel("Tapu Bulu", "Planta"),
new PokemonTipoPokemonModel("Tapu Koko", "Eléctrico"),
new PokemonTipoPokemonModel("Tapu Koko", "Hada"),
new PokemonTipoPokemonModel("Tapu Lele", "Hada"),
new PokemonTipoPokemonModel("Tapu Lele", "Psíquico"),
new PokemonTipoPokemonModel("Tauros", "Normal"),
new PokemonTipoPokemonModel("Tentacruel", "Agua"),
new PokemonTipoPokemonModel("Tentacruel", "Veneno"),
new PokemonTipoPokemonModel("Terrakion", "Lucha"),
new PokemonTipoPokemonModel("Terrakion", "Roca"),
new PokemonTipoPokemonModel("Throh", "Lucha"),
new PokemonTipoPokemonModel("Thundurus", "eléctrico"),
new PokemonTipoPokemonModel("Thundurus", "Volador"),
new PokemonTipoPokemonModel("Thundurus Incarnate", "Eléctrico"),
new PokemonTipoPokemonModel("Thundurus Incarnate", "Volador"),
new PokemonTipoPokemonModel("Thundurus Tótem - Therian", "Eléctrico"),
new PokemonTipoPokemonModel("Thundurus Tótem - Therian", "Volador"),
new PokemonTipoPokemonModel("Togekiss", "Hada"),
new PokemonTipoPokemonModel("Togekiss", "Volador"),
new PokemonTipoPokemonModel("Tornadus forma avatar", "Volador"),
new PokemonTipoPokemonModel("Torterra", "Planta"),
new PokemonTipoPokemonModel("Torterra", "Tierra"),
new PokemonTipoPokemonModel("Toucannon", "Normal"),
new PokemonTipoPokemonModel("Toucannon", "Volador"),
new PokemonTipoPokemonModel("Toxicroak", "Lucha"),
new PokemonTipoPokemonModel("Toxicroak", "Veneno"),
new PokemonTipoPokemonModel("Trevenant", "Fantasma"),
new PokemonTipoPokemonModel("Trevenant", "Planta"),
new PokemonTipoPokemonModel("Tsareena", "Planta"),
new PokemonTipoPokemonModel("Typhlosion", "Fuego"),
new PokemonTipoPokemonModel("Typhlosion Hisui", "Fantasma"),
new PokemonTipoPokemonModel("Typhlosion Hisui", "Fuego"),
new PokemonTipoPokemonModel("Tyranitar", "Roca"),
new PokemonTipoPokemonModel("Tyranitar", "Siniestro"),
new PokemonTipoPokemonModel("Tyrantrum", "Dragón"),
new PokemonTipoPokemonModel("Tyrantrum", "Roca"),
new PokemonTipoPokemonModel("Tyrunt", "Dragón"),
new PokemonTipoPokemonModel("Tyrunt", "Roca"),
new PokemonTipoPokemonModel("Unfezant", "Normal"),
new PokemonTipoPokemonModel("Unfezant", "Volador"),
new PokemonTipoPokemonModel("Ursaluna", "Normal"),
new PokemonTipoPokemonModel("Ursaluna", "Tierra"),
new PokemonTipoPokemonModel("Ursaring", "Normal"),
new PokemonTipoPokemonModel("Vanilluxe", "Hielo"),
new PokemonTipoPokemonModel("Vaporeon", "Agua"),
new PokemonTipoPokemonModel("Venusaur", "Planta"),
new PokemonTipoPokemonModel("Venusaur", "Veneno"),
new PokemonTipoPokemonModel("Victini", "Fuego"),
new PokemonTipoPokemonModel("Victini", "Psíquico"),
new PokemonTipoPokemonModel("Victreebel", "Planta"),
new PokemonTipoPokemonModel("Victreebel", "Veneno"),
new PokemonTipoPokemonModel("Vikavolt", "bicho"),
new PokemonTipoPokemonModel("Vikavolt", "eléctrico"),
new PokemonTipoPokemonModel("Vileplume", "Planta"),
new PokemonTipoPokemonModel("Vileplume", "Veneno"),
new PokemonTipoPokemonModel("Virizion", "Lucha"),
new PokemonTipoPokemonModel("Virizion", "Planta"),
new PokemonTipoPokemonModel("Wailord", "Agua"),
new PokemonTipoPokemonModel("Wairein", "Agua"),
new PokemonTipoPokemonModel("Wairein", "Hielo"),
new PokemonTipoPokemonModel("Walrein", "Agua"),
new PokemonTipoPokemonModel("Walrein", "Hielo"),
new PokemonTipoPokemonModel("Weavile", "Hielo"),
new PokemonTipoPokemonModel("Weavile", "Siniestro"),
new PokemonTipoPokemonModel("Weezing", "Veneno"),
new PokemonTipoPokemonModel("Wyrdeer", "Normal"),
new PokemonTipoPokemonModel("Wyrdeer", "Psíquico"),
new PokemonTipoPokemonModel("Xatu", "Psíquico"),
new PokemonTipoPokemonModel("Xatu", "Volador"),
new PokemonTipoPokemonModel("Xerneas", "Hada"),
new PokemonTipoPokemonModel("Xurkitree", "Eléctrico"),
new PokemonTipoPokemonModel("Yanmega", "Bicho"),
new PokemonTipoPokemonModel("Yanmega", "Volador"),
new PokemonTipoPokemonModel("Yveltal", "Siniestro"),
new PokemonTipoPokemonModel("Yveltal", "Volador"),
new PokemonTipoPokemonModel("Zacian", "Hada"),
new PokemonTipoPokemonModel("Zamazenta", "Lucha"),
new PokemonTipoPokemonModel("Zangoose", "Normal"),
new PokemonTipoPokemonModel("Zapdos", "Eléctrico"),
new PokemonTipoPokemonModel("Zapdos", "Volador"),
new PokemonTipoPokemonModel("Zarude", "Planta"),
new PokemonTipoPokemonModel("Zarude", "Siniestro"),
new PokemonTipoPokemonModel("Zekrom", "Dragón"),
new PokemonTipoPokemonModel("Zekrom", "Eléctrico"),
new PokemonTipoPokemonModel("Zoroark", "Siniestro"),
new PokemonTipoPokemonModel("Zoroark - Blanco", "Siniestro")

];

constructor() {
}
}